mbed-ce/mbed-os

- tools/requirements-ci-build.txt
- tools/requirements.txt
It's needed for local development (so that people can run mbedtools configure).
> Move mbed-tools to the main requirements.txt

- targets/upload_method_cfg/NUCLEO_F429ZI.cmake
- targets/upload_method_cfg/NUCLEO_L452RE_P.cmake
- tools/cmake/UploadMethodManager.cmake
Also remove "gdb_memory_map disable" command that breaks breakpoints.
> Fix gdbinit and make debug-xxx not working when executables are created outside of Mbed OS.

- hal/tests/TESTS/mbed_hal/sleep/main.cpp
- rtos/tests/TESTS/mbed_rtos/MemoryPool/main.cpp
- rtos/tests/TESTS/mbed_rtos/mail/main.cpp
- rtos/tests/TESTS/mbed_rtos/queue/main.cpp
- targets/upload_method_cfg/LPC1768.cmake
This adds a workaround for #32
Should stop some of the LPC1768 tests from failing!
None
------------------------------------------------------------------------------------------ …
> Disable mbed semihosting interface in tests, so as not to mess up their timing

- targets/upload_method_cfg/NUCLEO_F767ZI.cmake
This PR adds the cmake config for upload method of Nucleo-F767ZI
All methods except J-LINK have been tested (only for flash), for that reason is J-Link set to FALSE.
N/A
N/A
The list may need to be updated - https://github.com/mbed-ce/mbed-os/wiki/Mbed-CE-Officially-Supported-Targets-&-Features
[] No Tests required for this change (E.g docs …
> Add Cmake config for Nucleo-F767ZI into upload methods

- targets/upload_method_cfg/NUCLEO_F446RE.cmake
This PR adds the cmake config for upload method of Nucleo-F446RE
All methods have been tested (only for flash), but **for some reason ST-link method is not stable**, for more see logs below.
N/A
N/A
* The list may need to be updated - https://github.com/mbed-ce/mbed-os/wiki/Mbed-CE-Officially-Supported-Targets-&-Features.
* **For pyOCD is necessary to manually install a keil package**. It is descripted directly in Cmake config for now. …
> Add Cmake config for Nucleo-F446RE into upload methods

- targets/upload_method_cfg/NUCLEO_F303RE.cmake
This PR adds the cmake config for upload method of Nucleo-F303RE
All methods have been tested (only for flash), but for some reason ST-link method is not stable, for more see logs below.
**However, I probably found a solution for the Issue with unstable ST-link method. It will be in next PR.**
N/A
N/A
* The list may need to be updated - https://github.com/mbed-ce/mbed-os/wiki/Mbed-CE-Officially-Supported-Targets-&-Features.
* **For pyOCD is necessary to manually install a keil package**. It is descripted directly in Cmake config for now.
[] Feature update (New feature / Functionality change / New …
> Add Cmake config for Nucleo-F303RE into upload methods

- connectivity/FEATURE_BLE/source/cordio/TESTS/cordio_hci/driver/CMakeLists.txt
- connectivity/libraries/ppp/CMakeLists.txt
- connectivity/lorawan/CMakeLists.txt
- connectivity/nanostack/nanostack-hal-mbed-cmsis-rtos/CMakeLists.txt
- connectivity/netsocket/CMakeLists.txt
- connectivity/nfc/CMakeLists.txt
- events/CMakeLists.txt
- events/tests/TESTS/events/equeue/CMakeLists.txt
- events/tests/TESTS/events/queue/CMakeLists.txt
- events/tests/TESTS/events/timing/CMakeLists.txt
With the way the build system is set up now, it requires any code containing
```cpp
#ifdef MBED_CONF_RTOS_PRESENT
```
statements to be included in the mbed-core-sources CMake target.  This target gets built twice: once for baremetal, and once for RTOS.  So that way, the define actually gets triggered.  Other code is only built once, usually against the non-RTOS headers, so the define never gets triggered.  In most cases, this works, because individual libraries usually don't care if the RTOS is enabled.  I tried to clean up all the code that didn't comply with this (see #26).  But, as it turns out, mbed-events is not compatible with my scheme and uses RTOS defines.
The event queue library seems to have two different implementations: one for singlethreaded use, and one for multithreaded. …
> Fix event queue being stuck in non-RTOS mode, causing all sorts of weird behavior

- CMakeLists.txt
- tools/cmake/mbed_create_distro.cmake
- tools/cmake/mbed_set_linker_script.cmake
- tools/cmake/mbed_toolchain.cmake
This change rethinks how Mbed OS handles linker scripts with the GCC compiler, resolving #8.  Before, it would create one CMake target for each possible linker script.  Then, which of these got linked in to the final executable would determine which linker script was actually built and used.  This worked, but cluttered up the build with 50+ targets when only one was needed at any one time.
The new code works a bit differently.  Instead of actually creating a linker script target, `mbed_set_linker_script()` just sets an interface property on the MCU's CMake target.  This property is passed up to the top level by mbed_create_distro(), where it is then read out and used to set up one single `mbed-linker-script` target that points to the linker script we want to use.  This target is created …
> Change linker script handling logic to use only one linker script target

- targets/upload_method_cfg/NUCLEO_H743ZI2.cmake
- targets/upload_method_cfg/NUCLEO_L432KC.cmake
This PR adds the cmake config for upload method of Nucleo-L432KC adn Nucleo-H743ZI2.
All methods have been tested (only for flash) for both boards, but: 
* ST-link method is not recommended to use (is disabled) for L432.There seems to be a bug in ST-link (stlink.org release 1.7.0) and because of this the board is not able to restart it self after binary upload.Maybe there is also a small difference between st-link of Nuclelo-32 and Nucleo-64.
* J-link is not possible to use for Nucleo-H743ZI2, because St-link V3  is not supported in app St-link to J-link convertor (STLinkReflash).
N/A
N/A
N/A
[] …
> Add Cmake config for Nucleo-L432KC and Nucleo-H743ZI2 into upload methods

- targets/upload_method_cfg/NUCLEO_F303K8.cmake
- targets/upload_method_cfg/NUCLEO_L152RE.cmake
This PR adds the cmake config files for upload method of Nucleo-L152RE and Nucleo-F303K8 (Nucleo 32).
All methods have been tested (only for flash) for both boards, but the ST-link (stlink.org release 1.7.0) method is not recommended to use (is disabled) for L152. The ST-link keeps flashing and never stops.
N/A
N/A
N/A
[] No Tests required for …
> Add Cmake config files for Nucleo-L152RE and Nucleo-F303K8 into upload methods

- tools/cmake/mbed-run-greentea-test.in.cmake
- tools/cmake/mbed_greentea.cmake
- Print the command when a host test is being run.  This makes it easier to understand what the test runner is doing behind the scenes.  It looks like:
```
Executing: mbedhtrun --skip-flashing -f testshield-spi.bin -p COM3 -m NUCLEO_L452RE_P --baud-rate=115200
```
- While developing this, I noticed that one could get a free pass on all tests if `mbedhtrun` was not in your PATH.  Apparently failing to find an executable does not count as a "command error" in CMake?? I changed how it invokes mbedhtrun to fix this.
Working on testing documentation rn
[] Feature update (New feature / Functionality …
> Print the command when a greentea test is being run.  Also fix mbedhtrun not being on PATH causing all tests to pass!

- tools/cmake/mbed-run-greentea-test.in.cmake
- tools/cmake/mbed_generate_configuration.cmake
This MR fixes a bug with some recent changes involving the Python test runner.  Basically, calling it through `python -c` caused the exit code from the test runner to not be returned from Python.  So if tests failed, the command would still return exit code 0, and the test would be marked as passed.  Whoops.
To fix it, I added an exit() call, and did the same in another place vulnerable to this issue.
Makes tests able to fail again.
None …
> Fix issue with Python exit codes that masked failures

- hal/tests/TESTS/mbed_hal/common_tickers/main.cpp
In #44, @JohnK1987 noticed an issue where the LP Ticker test would intermittently hang on STMicro devices.  Scarily, this issue would go away from any of the following:
- Using an older GCC (<= 9.x)
- Adding any printfs in the test body
- Changing the serial baudrate to something other than 9600
- Running the test in the debugger from the start
Finally, I managed to isolate the problem by running the test normally, then connecting OpenOCD after it had already hung.
As it turns out, this is actually an integer overflow issue in the `ticker_interrupt_test()` test!  This test basically works by reading the current time into a variable (`tick_count`), setting some interrupts, waiting until the time is equal to `tick_count` plus some amount, and then reading flags from the interrupts.
Since …
> Fix overflow issue causing common tickers test to intermittently fail

- doxyfile_options
- drivers/include/drivers/I2C.h
- drivers/source/I2C.cpp
- hal/include/hal/i2c_api.h
- rtos/include/rtos/EventFlags.h
- storage/blockdevice/COMPONENT_I2CEE/source/I2CEEBlockDevice.cpp
- targets/TARGET_STM/i2c_api.c
- tools/test/ci/doxy-spellchecker/ignore.en.pws
The current Mbed OS I2C API has a number of issues that make it hard for users, especially new users, to program with it effectively.  These include:
- Very inconsistent return codes that make you constantly check the docs -- 1 is success from single-byte write() but failure from transaction write()??
- General lack of top-level documentation (what functions do I use for what, what are the gotchas, etc)
- No code examples for async or single-byte APIs
- Confusing information about how repeated starts work.  Leads to issues like https://github.com/ARMmbed/mbed-os/issues/15324 because it's not clear how to use the different APIs together with repeated starts.
- Lack of information about certain arguments, such as whether addresses need to be ORed with 1, or what happens if you provide both …
> Lots of usability improvements for the I2C API.  Better docs and new top-level functions.

- drivers/include/drivers/BufferedSerial.h
- drivers/include/drivers/SerialBase.h
- drivers/include/drivers/UnbufferedSerial.h
- platform/mbed_lib.json
This is something I've wanted to do for an eternity and a half.  It changes the default serial baudrate of Mbed to 115200 baud, instead of 9600 baud.  In recognition of the fact that it's not the 90s anymore, using 115200 baud allows you to print a lot more stuff without slowing your app down.  It should also provide a pretty significant speed boost to the test suite by making all the data print from the test 10x faster
stdio printfs will use 115200 baud unless configured otherwise.  BufferedSerial and UnbufferedSerial objects will use 115200 baud if the baudrate parameter is not set.
If anyone was relying on 9600 baud, they will have to add
```json
"platform.default-serial-baud-rate": 9600,
"platform.stdio-baud-rate": 115200
```
to their mbed_app.json in order to reenable the old …
> Change default serial baudrate to 115200

- targets/TARGET_Maxim/TARGET_MAX32620C/device/TOOLCHAIN_GCC_ARM/startup_max32620.S
This change fixes an issue that caused the linker to try to zero essentially all of the unused RAM, causing bin files for this target to be huge.  See the forum thread on this issue here: https://forums.mbed.com/t/how-do-i-build-an-example-program-using-vscode/18380/13?u=multiplemonomials
Smaller bin files and -250k flash consumption on MAX32620C.
None
None
--------------------------------------------------------------------------------------------------- …
> MAX32620C: Fix ASM that interfered with the GCC linker script and made the linker try to zero the entire RAM space

- targets/upload_method_cfg/DISCO_F769NI.cmake
small fix for upload method STM32CUBE on DISCO_F769NI:
add hwreset again. swreset did work only on every 2nd attempt.
------------------------------------------------------------- …
> add HW reset to upload for DISCO_F769NI STM32CUBE

- tools/cmake/mbed_toolchain.cmake
- tools/cmake/toolchains/GCC_ARM.cmake
This is a fix for the compiler warning for using the obsolete keyword 'register' and string conversions.
The register keyword is used in CMSIS, and should be fixed by updating CMSIS to a more recent version.
The string warning maybe fixed in the mbed-os repo, but there are a lot of places where it is used, so this fix should be considered as temporary workaround.
The warnings occur because mbed-ce does not use the compile profile settings from tools/profiles and uses C++17 as language standard. Beginning with c++17, gcc throws this warnings and it could be turned into errors in the future.
Reduces the large number of warning for an inital build
[x] Patch update (Bug fix / …
> add separate cxx options for gcc

- tools/cmake/mbed_target_functions.cmake
This PR is a feature upgrade to pass the depth of directory level to the memap.py. This allows a more detailed output of memory usage for compile units.
Memap.py has also the option to output a json file or a clickable html file.
Set default is set to no json, no html and depth = 2. It can be overriden in the top level CMakeLists.txt e.g.:
```
set(MBED_MEMAP_DEPTH "4" )
set(MBED_MEMAP_CREATE_JSON TRUE)
set(MBED_MEMAP_CREATE_HTML TRUE)
```
The settings are cached and can be changed also by using the CMake cache editor.
[x] Feature update (New feature / Functionality change / New API)
[] Major update …
> add depth setting, json and html output to memap report

- .github/workflows/basic_checks.yml
This fixes the license check CI failing due to https://github.com/nexB/scancode-toolkit/issues/3160 .
None
----------------------------------------------------------------------- …
> Fix license check CI failure

- tools/cmake/mbed_set_linker_script.cmake
- tools/cmake/mbed_target_functions.cmake
This is a PR for an additional feature:
a custom linker script can be applied by adding the .ld filepath as 2nd argument to mbed_set_post_build.
This PR replaces the draft #93 
E.g. in CMakeLists.txt for an executable:
```cmake
add_executable(Hello main.cpp)
target_link_libraries(Hello mbed-os)
mbed_set_post_build(Hello mbed-disco-f769ni-SRAM2.ld)
```
In this case, the .ld file must exist in the source dir of the project. The linker script is processed by the linker, so defines like in the mbed-os linkerscript templates can used in the same way.
The custom linker script is not applied to mbed built-in tests.
adding a custom linker script is supported now.
It is necessary to map variables or code to linker supplied sections. Especially for M4 or M7 MCUs with serveral busses and DMA …
> add custom linker script

- CMakeLists.txt
- tools/cmake/mbed_target_functions.cmake
This MR adds a feature for users to disable files that are part of one of the MCU targets (e.g. `mbed-stm32l4` or `mbed-stm32l452xe`.  It's as simple as:
```cpp
mbed_disable_mcu_target_file(mbed-stm32l452xe system_clock.c)
```
Then, you can add your own system_clock.c as part of a custom target.  No fuss, no muss!
It's now possible to replicate the 'override' functionality that custom targets had in Mbed CLI 1 and mbed-cmake!
None
This is documented through the mbed-ce-custom-targets example project.
[] Major update (Breaking change …
> Enable disabling target files for custom targets

- connectivity/FEATURE_BLE/CMakeLists.txt
- connectivity/FEATURE_BLE/libraries/TARGET_CORDIO_LL/CMakeLists.txt
- targets/TARGET_STM/stm_i2c_api.h
In #78 , I deleted some variables because I thought they were unused.  Turns out they weren't, whoops.  This adds them back.
Targets that are STATIC_PINMAP_READY will compile again.
[] Tests / results supplied as part of …
> Fix compilation of I2C code on static pinmap targets

- targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/TOOLCHAIN_GCC_ARM/STM32F303XC.ld
- targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/cmsis_nvic.h
This fix is for correcting the ram size of F303CC device. 
In total RAM+RAM1 it has 48 kB, but the regions are not continuous. SRAM has 40 kB, when 48 kB is set in the linker script, then the device fails to start because the stack pointer is in the Nirvana.
This error is also in arm-pack index.json in Mbed-OS.
Important fix for this device. Currently, no boards are using this. It is a basically needed for new target ROBOTDYN_F303CC
(also called Blackpill F303, small Chinese breakout board).
[] Major update (Breaking change E.g. …
> device ram size is 40 kb, not 48 kB

- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/serial_api.c
This applies the patch found in this issue: https://github.com/ARMmbed/mbed-os/issues/15342 .  The code for MIMRT serial_format() was obviously broken as it is using a uint8_t to store the 32-bit CTRL register:
serial_format() was obviously broken on MIMXRT105x targets.
None
[] …
> Fix MIMXRT105x serial_format() not working

- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_GCC_ARM/MIMXRT1052xxxxx.ld
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/mbed_overrides.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/device/usb_device_ehci.c
This MR fixes the ncache region of memory so that it's correctly marked in the MPU as non-cached again.  It is now located in the previously-unused DTCM memory (also freeing up some space for user stuff in OCRAM).  This was broken by #130.  The ncache region is important because DMA buffers on the MIMXRT can't be read properly if they are in a region covered by the CPU cache.
None
--------------------------------------------------------------------------- …
> MIMXRT: Make ncache region non-cached again

- cmsis/device/rtos/source/mbed_rtx_idle.cpp
- connectivity/FEATURE_BLE/include/ble/gatt/GattCharacteristic.h
- drivers/tests/UNITTESTS/doubles/drivers/LowPowerTicker.h
- events/source/equeue_mbed.cpp
- hal/tests/TESTS/mbed_hal/lp_ticker/main.cpp
- hal/tests/TESTS/mbed_hal/rtc/main.cpp
- hal/tests/TESTS/mbed_hal/sleep/main.cpp
- platform/cxxsupport/mstd_type_traits
- platform/include/platform/mbed_power_mgmt.h
- platform/source/mbed_os_timer.cpp
- platform/tests/UNITTESTS/doubles/mbed_assert_stub.cpp
- rtos/tests/UNITTESTS/doubles/Mutex_stub.cpp
This PR adds various fixes that we needed for our project (https://github.com/leka/LekaOS) to be able to use GCC v11 and C++20
- Fix rtos::Mutex stub, add trylock() method
- LowPowerTicker - Add ::attach(...) method + call callback
- mbed_power_management - rename sleep --> mbed_sleep to avoid conflicts
- GCC 11/C++ 20 - Remove deprecated type_traits
- GCC 11/C++ 20 - Remove redundant templating of methods
- Warning - pragma ignore invalid-noreturn for unit tests
> mbed-ce@master + fixes + gcc 11 support 

- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1170/TARGET_EVK/serial_api.c
This imports the second change from https://github.com/ARMmbed/mbed-os/pull/15382/
This should fix serial_format() on MIMXRT1170.  It was obviously broken due to storing a 32-bit register value in an 8-bit variable.
None
[] …
> Fix serial_format() on MIMXRT1170 as well

- tools/cmake/mbed_ide_debug_cfg_generator.cmake
Add `negative` option (default to true) to **not** configure vscode
None
None
Not sure what to do -- having the default configure vscode is good for new comers but it's a pain for people wanting to integrate mbed-ce in their project where they might have a lot already set up.
> (vscode + cmake) Add option to NOT config vscode

- connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_2/CMakeLists.txt
- connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_MS/CMakeLists.txt
Fixes #138 
With this change, if the BlueNRG components are used, mbed-ble can now be only used with the RTOS, not with mbed-baremetal.  That's what I had tried to avoid by making BlueNRG a different library...
[] Tests / …
> Fix BlueNRG undefined reference to ble_cordio_get_hci_driver()

- connectivity/mbedtls/platform/inc/platform_mbed.h
When I attempted to run [the sockets example](https://github.com/mbed-ce/mbed-os-example-sockets) in TLS mode, I got an extremely cryptic error related to certificate parsing.  Eventually, I was able to track this down to https://github.com/ARMmbed/mbed-os/issues/8638 .  Turns out that, to save space, the Mbed devs disabled the SHA1 algorithm by default.  However, this algorithm is still used for a number of root CA certificates, including the one used in the example.  I sort of understand the motivation to leave it off, but the errors it causes are just too damn cryptic.  It should be turned on until and unless a better error handling system can be created to tell the user when it's needed.
The TLS sockets example will now work.
None …
> Fix TLS example by enabling SHA-1 certificates out of the box

- storage/blockdevice/COMPONENT_QSPIF/source/QSPIFBlockDevice.cpp
- targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_qspi.c
On the STM32769NI the STM32 BSP has an issue where QSPI accesses timeout and require a chip reset. Mbed use to contain a patch to fix this similar to this one but the change was lost during an update.
Enable the workaround ST uses for specific F7 chips but on all chips. There's no downside to this from what I can tell.
The 4-byte addressing was disabled because of timeouts which I think are due to this issue but falsely misattributed to 4-byte addressing. Enable that again.
Further discussions:
https://github.com/ARMmbed/mbed-os/issues/10049
https://github.com/ARMmbed/mbed-os/issues/15108
https://github.com/STMicroelectronics/STM32CubeF7/issues/52
https://github.com/STMicroelectronics/STM32CubeF7/issues/82
None
------------------------------------------------------------------------------- …
> STM32F7 QSPI flash timeouts and 4-byte addressing

- targets/TARGET_STM/i2c_api.c
When testing with a U-Blox GPS, I noticed that there's an issue in the new STM32 I2C HAL added by #78 .  Trying to do a repeated start using the transactional API:
```cpp
// Set read address to 1
uint8_t const readAddr = 0x01;
TEST_ASSERT_EQUAL(I2C::Result::ACK, i2c->write(EEPROM_I2C_ADDRESS, reinterpret_cast<const char *>(&readAddr), 1, true));
// Read the byte back
uint8_t readByte = 0;
TEST_ASSERT_EQUAL(I2C::Result::ACK, i2c->read(EEPROM_I2C_ADDRESS | 1, reinterpret_cast<char *>(&readByte), 1));
TEST_ASSERT_EQUAL_UINT8(0x3, readByte);
```
simply does not work:
This is because the code in get_hal_xfer_options() was returning `I2C_LAST_FRAME` for the case of stop=false, which is patently wrong -- it should be `I2C_FIRST_FRAME`, to indicate that we want a start condition but not a stop. …
> STM32 I2C v2 HAL: Fix repeated starts in transaction mode

- hal/include/hal/flash_api.h
- hal/tests/TESTS/mbed_hal/flash/functional_tests/main.cpp
- targets/TARGET_NXP/TARGET_LPC176X/device/flash_api.c
This fixes an issue reported on the forums here: https://forums.mbed.com/t/limitation-of-flash-iap-for-lpc176x-flashing-from-ram-only/19892
The LPC1768's FlashIAP implementation could not successfully copy flash data to flash.  Now, I adapted the existing RAM buffer scheme in the driver to fix this issue.  I also did a general cleanup of the lpc1768 flash code, including replacing the magic 1024 number with the page size, and fixing the reported deadlock issue if an operation fails (missed core_util_critical_section_exit() calls).
[] …
> Bugfix: LPC1768 IAP could not copy flash to flash

- connectivity/lwipstack/source/lwip_tools.cpp
When IPv6 is prefered it will choose a link local address on a network that lacks IPv6 over a working IPv4 network, breaking networking. Change this behaviour to prefer a link local address only as a last resort.
This also changes LWIP::get_ipv6_addr to not return link local addresses. Use get_ipv6_link_local_addr instead for this.
This fixes preferring IPv6 on IPv4-only networks.
This might break the API for applications that rely on link local addresses coming from get_ipv6_addr
[] Major update (Breaking change E.g. Return code …
> LWIP::get_ip_addr: Prefer IPv4 over IPv6 link local addresses

- drivers/include/drivers/I2C.h
- drivers/include/drivers/SPI.h
- drivers/mbed_lib.json
- drivers/source/SPI.cpp
- hal/include/hal/dma_api.h
- hal/include/hal/spi_api.h
- targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device.h
- targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device.h
- targets/TARGET_RENESAS/TARGET_RZ_A2XX/TARGET_GR_MANGO/device.h
- targets/TARGET_TOSHIBA/TARGET_TMPM46B/device.h
- targets/TARGET_TOSHIBA/TARGET_TMPM4G9/device.h
- targets/TARGET_TOSHIBA/TARGET_TMPM4GR/device.h
- targets/TARGET_TOSHIBA/TARGET_TMPM4NR/device.h
- targets/targets.json
- tools/test/ci/doxy-spellchecker/ignore.en.pws
I split this PR off from my DMA SPI PR, to try and reduce the size of that below the Schwarzschild radius.  Its goal is to improve the usability of the SPI class by adding convenience functions, and to vastly increase the amount of documentation available for SPI.  Specifically, it:
- Documents previously cryptic things like frame sizes, transaction queueing, GPIO CS usage, and DMA hints
- Provides usage examples for basically all of the major ways to use the SPI class
- Converts the `TRANSACTION_QUEUE_SIZE_SPI` define into a proper mbed_app.json option (what it should have been in the first place).  This provides a standard way for the user to modify it -- before, it was just set in a bunch of random manufacturer header files and target definitions and could not be modified.
- Provides …
> Improve usability and documentation of the SPI API

- connectivity/drivers/wifi/CMakeLists.txt
- rtos/tests/UNITTESTS/doubles/rtos/Mutex.h
- storage/blockdevice/COMPONENT_OSPIF/include/OSPIF/OSPIFBlockDevice.h
- storage/blockdevice/COMPONENT_OSPIF/mbed_lib.json
- storage/blockdevice/COMPONENT_OSPIF/source/OSPIFBlockDevice.cpp
- storage/blockdevice/COMPONENT_QSPIF/include/QSPIF/QSPIFBlockDevice.h
- storage/blockdevice/COMPONENT_QSPIF/source/QSPIFBlockDevice.cpp
- storage/platform/CMakeLists.txt
- targets/targets.json
- targets/upload_method_cfg/B_U585I_IOT02A.cmake
- targets/upload_method_cfg/openocd_cfgs/stm32u5x.cfg
- tools/cmake/UploadMethodManager.cmake
@tim35ca on the forums [pointed out](https://forums.mbed.com/t/octal-spi-on-b-u585/20539/4) that declaring an OSPIFBlockDevice as a global object can cause it to not work correctly.  This is because the author of OSPIFBlockDevice made a common mistake: interacting with global variables in an object constructor, without realizing that those global variables might not yet have been initialized.  The C++ environment is free to initialize globals in any order it wants, so depending on your luck for the day and the direction of the wind, the globals in OSPIFBlockDevice.cpp may or may not have been initialized by the time your globally declared block device instance gets constructed.
If they aren't, you will likely get a HardFault due to accessing a null `_active_ospif_flash_csel_arr` pointer. …
> Fix declaring OSPIFBlockDevice and QSPIFBlockDevice as globals, fix some STM32U585 issues

- connectivity/CMakeLists.txt
- targets/upload_method_cfg/DISCO_L072CZ_LRWAN1.cmake
@tim35ca on the forums reported this compile error, turns out that the subdirectory order has been incorrect since I refactored that part of the build system.  Easily fixed by reordering the add_subdirectory() calls.
I also threw in an upload configuration file for DISCO_L072CZ_LRWAN1, so uploading to the board should work properly now.
Mbed CE now compiles for boards with LoRaWan
None
---------------------------------------------------------------------- …
> Fix LoRaWan compile error, add DISCO_L072CZ_LRWAN1 upload method configuration

- connectivity/drivers/lora/COMPONENT_SX1272/SX1272_LoRaRadio.cpp
- connectivity/drivers/lora/COMPONENT_SX1276/SX1276_LoRaRadio.cpp
- connectivity/lorawan/include/lorawan/LoRaRadio.h
Compiling using arm gnu toolchain arm-none-eabi/12.2 and target DISCO_L072CZ_LRWAN1 produced errors for SX1276 modem::get_status() return type, i.e. two places declared as uint8_t and another radio_status_t.
Same fix for SX1272 modem.
Fixes #20741.  
Mbed CE now compiles for boards with LoRaWan and 
None.
None.
[] No Tests required for this …
> Bug fix/lorawan sx127x get status type

- drivers/include/drivers/SPI.h
- drivers/source/SPI.cpp
- hal/include/hal/spi_api.h
This MR performs more cleanups to the SPI driver which are required for DMA SPI to work correctly.  While running tests, I noticed a number of issues that have just got to get fixed.
<h3>Interaction between async APIs and the SPI::select() function</h3>
Previously, the asynchronous APIs did not know about the select() function -- they would always deselect the chip at the end of a transfer, regardless of whether you had called select() before or not.
Now, I've implemented a new mechanism in the async IRQ handler which checks if the select count was more than 1 before and doesn't deselect the chip if so.  This allows an asynchronous operation to be used as only *part* of a larger transfer, which opens up some new ways to use SPI.
<h3>spi_free() never called</h3>
For whatever reason, the …
> SPI Driver API bugfixes and cleanup, part 2

- storage/blockdevice/COMPONENT_SD/include/SD/SDBlockDevice.h
- storage/blockdevice/COMPONENT_SD/source/SDBlockDevice.cpp
Some time ago, in 0874f74a, I updated the SDBlockDevice class to support HW chip selects.  My intention was to use this as part of the CI test shield test suite, so that hardware CS functionality could be tested.  However, after looking at the SDBlockDevice code and the SPI code more closely, I realized that this cannot work.  The reason is, SDBlockDevice relies on keeping CS low across multiple transfers, but that is currently impossible when using hardware CS control with Mbed (even though I bet that most chips support it...).
So, I reverted that commit, expunging the HW CS constructors that were added.
However, for my DMA SPI test suite, I do need to be able to run at least some of the operations in SDBlockDevice with DMA, so that I can prove that DMA works the same as regular SPI. …
> SDBlockDevice: revert HW CS support, add async support

- platform/source/mbed_retarget.cpp
Versions of GCC which supply newer Newlib versions (unsure of the exact Newlib version, I think it's the one included with GCC 11 and newer) now appear to want the _getpid() and _kill() functions defined.  I checked using radare, and it appears they get pulled in as dependencies of the C++ standard library, which has been built with exception handling enabled and therefore calls things like abort().  So, these warnings will show up whenever someone links an application which uses STL features.
In the long term the best solution is to rebuild the STL with exceptions disabled, or switch to a toolchain which has that done for us, but in the meantime this will stop the warnings from bothering people.
None
None
None
------------------------------------------------------------------------------- …
> Fix warnings from kill and getpid not being implemented

- CMakeLists.txt
- drivers/include/drivers/FlashIAP.h
- hal/include/hal/flash_api.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/CMakeLists.txt
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/TARGET_1050_EVK/xip/evkbimxrt1050_flexspi_nor_config.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/TARGET_1060_EVK/xip/evkbmimxrt1060_flexspi_nor_config.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/device.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/flash_api.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/flash_defines.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/mimxrt_flash_api.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/mimxrt_memory_info.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_TEENSY_4X/TARGET_TEENSY_40/mimxrt_memory_info.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_TEENSY_4X/TARGET_TEENSY_41/mimxrt_memory_info.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_TEENSY_4X/bootdata.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/device/TOOLCHAIN_GCC_ARM/MIMXRT1052xxxxx.ld
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/drivers/fsl_flexspi.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/lpm.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/lpm.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/mbed_overrides.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/mimxrt_clock_adjustment.c
- targets/targets.json
- tools/cmake/mbed_set_linker_script.cmake
- tools/cmake/mbed_toolchain.cmake
- tools/cmake/upload_methods/UploadMethodLINKSERVER.cmake
I will say that, this PR was a journey.  I started off with a simple-ish goal: adding Flash API support for the MIMRT1060 EVK.  Since the MIMXRT1050, which is basically the same silicon, already supports Flash, this should be easy... right?
Well, not so much.  I started by doing a bit of a refactor of how flash information is tracked for MIMXRT105x devices.  Instead of putting some of it it as defines in targets.json, and some of it in device.h, it all now lives in a header which is specific to each target, `mimxrt_memory_info.h`.  This way we can collect all of these constants in one place that's easy to modify when adding a new MIMXRT105x family target (and hopefully other MIMXRT targets later on as well!).  This basically worked, and meant that I could easily adapt the MIMXRT1050_EVK …
> Refactor flash setup for MIMXRT105x devices, add flash API support for MIMXRT1062 EVK

- .github/workflows/basic_checks.yml
- drivers/mbed_lib.json5
- targets/targets.json5
- tools/python/mbed_tools/build/_internal/config/assemble_build_config.py
- tools/python/mbed_tools/lib/json_helpers.py
- tools/python/mbed_tools/project/_internal/project_data.py
- tools/python/python_tests/mbed_tools/lib/test_json_helpers.py
- tools/python/python_tests/mbed_tools/project/_internal/test_project_data.py
- tools/python/python_tests/mbed_tools/project/factories.py
- tools/python/python_tests/mbed_tools/regression/test_configure.py
- tools/requirements.apt.txt
- tools/requirements.txt
Too long we have suffered under the heel of the oppressive JSON parser and its hatred of comments!  Mbed OS has loads of config files with all sorts of complicated settings in them.  I'm sure that there are very good reasons why these settings are how they are, but much of this information has been lost to time because these JSON config files didn't allow comments.
No longer!  Starting today, we have the option to write any and all JSON config files in the JSON5 standard instead.  JSON5 is similar to JSON, except that it allows C-style comments in the code!  So, we can now write comments for target, library, and application settings.  Truly this is the beginning of a new era!
mbed_lib.json, mbed_app.json, and custom_targets.json may now optionally be written as json5.  The file extension …
> Allow Mbed config files to be json5 in addition to json

- drivers/include/drivers/I2C.h
- targets/TARGET_STM/i2c_api.c
Found a minor I2C issue when doing testing with the CI shield v2.  When you do an I2C async transfer that is both a write and a read, it should do the write first, then a repeated start, then the read.  This is worth doing for 3 reasons:
1. It's slightly more efficient in terms of data rate on the bus
2. In multi-master applications, it ensures that nothing else can use the bus between the write and the read
3. A small percentage of chips (e.g. the U-Blox MAX-8) require repeated starts and won't work without them.
However, the stm32 I2C HAL was not doing repeated starts, and instead was generating something like
```
Start Wr[0xa0] Ack 0x00 Ack 0x01 Ack Stop Start Rd[0xa1] Ack 0x02 Nack Stop
```
Now, with this patch, a single transfer call always does a repeated start:
```
Start Wr[0xa0] …
```
> Fix STM32 I2C v2 async transfer not doing a repeated start

- drivers/include/drivers/SPI.h
- drivers/source/SPI.cpp
- hal/include/hal/spi_api.h
- platform/include/platform/CacheAlignedBuffer.h
- storage/blockdevice/COMPONENT_SD/include/SD/SDBlockDevice.h
- storage/blockdevice/COMPONENT_SD/source/SDBlockDevice.cpp
- targets/TARGET_Cypress/TARGET_PSOC6/cy_spi_api.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/spi_api.c
- targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/spi_api.c
- targets/TARGET_NUVOTON/TARGET_M2354/spi_api.c
- targets/TARGET_NUVOTON/TARGET_M251/spi_api.c
- targets/TARGET_NUVOTON/TARGET_M261/spi_api.c
- targets/TARGET_NUVOTON/TARGET_M451/spi_api.c
- targets/TARGET_NUVOTON/TARGET_M460/spi_api.c
- targets/TARGET_NUVOTON/TARGET_M480/spi_api.c
- targets/TARGET_NUVOTON/TARGET_NANO100/spi_api.c
- targets/TARGET_NUVOTON/TARGET_NUC472/spi_api.c
- targets/TARGET_RENESAS/TARGET_RZ_A1XX/spi_api.c
- targets/TARGET_RENESAS/TARGET_RZ_A2XX/spi_api.c
- targets/TARGET_STM/TARGET_STM32H7/STM32Cube_FW/STM32H7xx_HAL_Driver/stm32h7xx_hal_dma_ex.c
- targets/TARGET_STM/stm_spi_api.c
- targets/TARGET_STM/stm_spi_api.h
- targets/TARGET_Silicon_Labs/TARGET_EFM32/spi_api.c
- targets/TARGET_TOSHIBA/TARGET_TMPM46B/spi_api.c
- targets/TARGET_TOSHIBA/TARGET_TMPM4G9/spi_api.c
- targets/TARGET_TOSHIBA/TARGET_TMPM4GR/spi_api.c
- targets/TARGET_TOSHIBA/TARGET_TMPM4NR/spi_api.c
- tools/python/run_python_tests.sh
- tools/python/scancode_evaluate/scancode_evaluate.py
I started this effort to track down some DMA SPI issues that were showing up in the test cases for Nucleo H743ZI.  I thought there might just be some random bugs in the HAL driver, and I did in fact find two such issues.  However, I also found a more serious problem: the DMA SPI code did not correctly manage the cache for Cortex-M7 devices which have a CPU cache.
For the initial DMA SPI implementation, I thought it would be enough to just invalidate the cache for the Rx buffer after the transfer is over.  And this *almost* works -- it does ensure that the correct Rx data gets read out at the end of the transfer.  However, if there are any other variables being stored in the same cache lines as the Rx data, these can actually be corrupted, because the variable could be up to date in the …
> Make DMA SPI driver aware of CPU cache, fix data corruption and other SPI issues on STM32H7

- storage/kvstore/kv_config/CMakeLists.txt
- storage/platform/CMakeLists.txt
lfsv2 missing from cmake storage-platform and storage-kv-config
add "mbed-storage-littlefs-v2" to cmake mbed-storage-libs list
add "mbed-storage-littlefs-v2" to cmake mbed-storage-kv-config link libraries
None
[X] No Tests required for this change (E.g docs only update)
[] Tests / …
> lfsv2 missing from cmake storage: platform and kv-config

- platform/mbed_lib.json
- targets/TARGET_RASPBERRYPI/TARGET_RP2040/analogin_api.c
- targets/TARGET_RASPBERRYPI/TARGET_RP2040/objects.h
- targets/TARGET_RASPBERRYPI/TARGET_RP2040/pwmout_api.c
- targets/targets.json5
@Olivier_Corrio on the Mbed forums reported an [issue](https://forums.mbed.com/t/pwm-period-is-not-good-on-mbed-with-raspberry-pico/22151) with the PWM functionality on RPi Pico.  After some investigation, I confirmed the issue: The initial implementation of PWM always uses a top_count of 1000 and only varies the divider to set the PWM period.  I think they did it this way to avoid floating point math, but it is sub-optimalfor three reasons:
- Low duty cycle resolution of the PWM -- only 1/1000 increments when it could be 1/65536 increments
- High minimum PWM period -- with a divider of 1 and a top_count of 1000, the minimum PWM period is 8us, even though the hardware supports sub 1us periods (with top_count lower than 1000)
- Low maximum PWM period -- with a divider of 256 and a …
> Increase RPi Pico PWM range and resolution to the max supported by HW

- targets/TARGET_STM/tools/STM32_gen_PeripheralPins.py
In this PR I did small update of STM32_gen_PeripheralPins.py for protection against using python version older than python3+ and should be solution for #212 
Before this PR:
```
D:\Mbed\MbedCE\MbedCE_test\mbed-os\targets\TARGET_STM\tools>STM32_gen_PeripheralPins.py -m "STM32U575RGTx.xml"
Script version 1.20.5
Checking STM32_open_pin_data repo...
*** git clone https://github.com/STMicroelectronics/STM32_open_pin_data.git ***
*** git clone done
STM32_open_pin_data DB version STM32CubeMX-DB.6.0.90
* Output directory: D:\Mbed\MbedCE\MbedCE_test\mbed-os\targets\TARGET_STM\tools\TARGET_CUSTOM\TARGET_STM\TARGET_STM32U5\TARGET_STM32U575xG\TARGET_STM32U575RGT
* Generating PeripheralPins.c and PinNames.h with 'STM32_open_pin_data\mcu\STM32U575RGTx.xml'
* GPIO file: …
```
> Update STM32_gen_PeripheralPins.py for #212

- platform/source/mbed_rtc_time.cpp
- targets/TARGET_STM/README.md
- targets/TARGET_STM/mbed_overrides.c
- targets/targets.json5
This is a fix for the RTC issues that [@sunnydaywest](https://forums.mbed.com/t/time-null-of-rtc-example-not-synchronizing-with-rtc-when-using-battery/22248) reported on the forums, and also as ARMmbed/mbed-os#15487.
As I explained in the thread, the easiest way to fix the issue is to update gettimeofday() to not reset the RTC time.  It's not intuitive for _getting_ the time to _reset_ the time, just because you didn't call rtc_init() first. 
While I was in the RTC code, I also took the opportunity to:
- Remove code from mbed_overrides.c which is also in rtc_api.c.  As far as we could tell, the code in rtc_api.c is the correct version, and it's what gets executed second so it makes sense for it to be the correct one.
- Move `target.lse_bypass` option to be for all STM32 targets, as this …
> [draft] Don't reset the RTC time from gettimeofday(), plus other RTC cleanups

- targets/TARGET_STM/TARGET_STM32U5/TARGET_STM32U575xG/cmsis_nvic.h
- targets/TARGET_STM/TARGET_STM32U5/TARGET_STM32U575xG/system_clock.c
- targets/targets.json5
MCU family MCU_STM32U575xG:
- ROM and RAM size
- Added support for HSE and LSE MSI auto calibration
- Added USB clock config
Has been discussed in mbed ce tickets.
[x] Feature update (New feature / Functionality change / New API)
[x] Tests / results supplied as part of this PR
Tests with …
> Add target hse u575xg

- tools/cmake/upload_methods/FindSTLINKTools.cmake
Based on [this discussion](https://github.com/mbed-ce/mbed-os/discussions/225) this PR update FindSTLINKTools.cmake to use also STM32CubeCLT (new standalone Command Line Tool for STM32) before were necessary to install whole STM32CubeIDE.
The script check for STM32CubeIDE and also for STM32CubeCLT location, then use one of them but CLT has priority (if both are installed CLT is used anyway).
User can choose if is necessary to install whole IDE or just CLT.
But I am not able to test it on Linux or MAC!!!
EDIT: Already tested on Linux (by Jamie) with necessary feedback for modification.
N/A
Was updated - https://github.com/mbed-ce/mbed-os/wiki/Upload-Methods#stm32cube
[X] Patch …
> Update FindSTLINKTools.cmake for STM32CubeCLT

- tools/cmake/app.cmake
This PR is in context of many discussions and I hope everyone will find its option.
* [#233](https://github.com/mbed-ce/mbed-os/pull/233)
* https://github.com/mbed-ce/mbed-os/discussions/112
In current state Mbed CE build system auto searches only for upload method config for regular targets. In case of custom targets is expected the config will be defined via top level cmakelist.
```
// this is example how look current structure of a project with a custom target
./Project_Name/
│
├── mbed-os/
├── Build/
├── Custom_targets/
│   ├── YOUR_TARGET/
│   │	└──  somefiles.xxx
│   ├── ANOTHER_TARGET/
│   │	└──  somefiles.xxx
│   └──	CMakeLists.txt
│
├── CMakeLists.txt
├── mabed_app.json
├── custom_targets.json
└── main.cpp
```
This PR brings the build system will also search for an upload method …
> Add feature for auto search of upload method config for custom targets

- connectivity/netsocket/CMakeLists.txt
- targets/targets.json5
This fixes a build error that was happening after #247 for targets that did not have any wifi drivers when you linked mbed-netsocket.  The issue is that if you pass a non-existant library to a target_link_libraries() call, CMake thinks it's a system library and tries to link it with -l (legacy behavior), causing a linker error rather than a CMake error as it should.  Thanks to @JojoS62 for diagnosing the issue!
mbed-netsocket should be usable again... oops
None
[] Major update (Breaking change E.g. Return code change / API behaviour …
> Bugfix: Only link mbed-wifi if it exists for this target

- .github/workflows/basic_checks.yml
- .github/workflows/greentea_cmake.yml
- .github/workflows/test_building_multiple_executables.yml
- tools/cmake/app.cmake
- tools/cmake/mbed_generate_configuration.cmake
- tools/cmake/mbed_python_interpreter.cmake
Using Mbed lately, and watching others use it, I have been feeling like the need to install Python packages, and to reinstall them if Mbed adds a new requirement, causes annoyance for people a lot of the time.  Traditionally I've been a bit of a critic of venvs but as I have gotten more into Python development I have understood their value more.  It's simply too common to have broken system packages, or a system with a too old version of a package, or a dependency conflict with something else you have installed.
While it's still nice to have the option to use system packages if needed, making the default to create a new venv with all the correct stuff seems like it will make Mbed more user friendly, and therefore, is worth doing.  The venv uses about 60MB per instance on my machine, which …
> Use a virtual environment for Python packages by default

- targets/TARGET_STM/serial_api.c
- targets/targets.json5
USC RPL noticed another bug: on STM32H7, if you set the LPUART to run at higher than 9600 baud, data is not transmitted (& presumably received) correctly.  @qwertyquerty noticed that when he set 115200 baud, he was actually getting 960 baud!  I suspect that noone noticed this before because LPUART is more commonly used at lower baudrates, but it's actually better than the regular UART peripherals (it has a FIFO though Mbed currently does not enable the FIFO), so no reason not to use it at higher baudrates too.
Digging into it a bit, it looks like what happens is, the serial_api.c code checks the baudrate, and if it's too low to run off the LSE oscillator, it falls back to the next configured clock source.  By default, on STM32H7, that is PLL2.  However, we don't actually use PLL2 in code, …
> Fix STM32H7 LPUART clock source being incorrect for higher baudrates

- storage/blockdevice/CMakeLists.txt
- storage/blockdevice/tests/TESTS/CMakeLists.txt
- storage/blockdevice/tests/TESTS/blockdevice/CMakeLists.txt
- storage/blockdevice/tests/TESTS/blockdevice/buffered_block_device/CMakeLists.txt
- storage/blockdevice/tests/TESTS/blockdevice/flashsim_block_device/CMakeLists.txt
- storage/blockdevice/tests/TESTS/blockdevice/general_block_device/CMakeLists.txt
- storage/blockdevice/tests/TESTS/blockdevice/general_block_device/main.cpp
- storage/blockdevice/tests/TESTS/blockdevice/heap_block_device/CMakeLists.txt
- storage/blockdevice/tests/TESTS/blockdevice/mbr_block_device/CMakeLists.txt
- storage/blockdevice/tests/TESTS/blockdevice/util_block_device/CMakeLists.txt
This PR reactivates the tests of all the block devices under storage/blockdevices,  Looking at these tests initially I had thought that they were just for the "software" block devices like SlicingBlockDevice, but actually no: the "general" block device test actually tests all the hardware block device drivers if they exist on the current target.
I set up the build system for these tests so that they should now be able to run again.
None …
> Reactivate block device tests

- hal/include/hal/serial_api.h
- hal/include/hal/static_pinmap.h
- targets/TARGET_NXP/TARGET_LPC176X/PeripheralNames.h
- targets/TARGET_NXP/TARGET_LPC176X/PeripheralPinMaps.h
- targets/TARGET_NXP/TARGET_LPC176X/TARGET_ARCH_PRO/PinNames.h
- targets/TARGET_NXP/TARGET_LPC176X/TARGET_MBED_LPC1768/PinNames.h
- targets/TARGET_NXP/TARGET_LPC176X/analogin_api.c
- targets/TARGET_NXP/TARGET_LPC176X/analogout_api.c
- targets/TARGET_NXP/TARGET_LPC176X/can_api.c
- targets/TARGET_NXP/TARGET_LPC176X/i2c_api.c
- targets/TARGET_NXP/TARGET_LPC176X/pwmout_api.c
- targets/TARGET_NXP/TARGET_LPC176X/serial_api.c
- targets/TARGET_NXP/TARGET_LPC176X/spi_api.c
- targets/targets.json5
This PR updates LPC1768 to support static pinmaps.  This means that pins can be mapped at compile time instead of at runtime, like:
```
constexpr auto spiPinmap = get_spi_pinmap(PIN_SPI_MOSI, PIN_SPI_MISO, PIN_SPI_SCLK);
spi = new SPI(spiPinmap);
```
To be honest, a lot of the reason I made this PR is I wanted to learn about the static pinmap system, since I had not used it before.  And I figured, may as well do something useful while I'm learning it!  Plus, this way LPC1768 users can save some ROM space and execution time by taking advantage of the static pinmap support.
- Static pinmaps now supported on LPC1768
[X] Patch update (Bug fix / Target update / Docs update / Test …
> LPC1768: Support static pinmaps

- drivers/source/PwmOut.cpp
- storage/blockdevice/COMPONENT_SD/mbed_lib.json
- storage/blockdevice/COMPONENT_SPIF/mbed_lib.json
- targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/CMakeLists.txt
- targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_ARDUINO_NICLA_SENSE_ME/PinNames.h
- targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_ARDUINO_NICLA_SENSE_ME/device.h
- targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_GCC_ARM/NRF52832.ld
- targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/cmsis_nvic.h
- targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/nrf52832_memory_regions.h
- targets/drivers.json5
- targets/targets.json5
- targets/upload_method_cfg/ARDUINO_NICLA_SENSE_ME.cmake
This PR adds support for Arduino Nicla Sense ME.  Arduino sent me a free test unit a while back so figured I may as well give it a shot.  This one ended up actually being pretty easy to work with because, unlike most Arduinos, it has a standard Mbed CMSIS-DAP interface chip on it, no weird bootloader hijinks needed.  Basically just had to add the PinNames.h, the CMake file, and the targets.json definition.
https://github.com/mbed-ce/mbed-os/wiki/MCU-Info-Page:-Arduino-Nicla-Sense-ME
[] Major update (Breaking change E.g. Return code …
> Add Arduino Nicla Sense ME support

- drivers/include/drivers/I2CSlave.h
- hal/include/hal/i2c_api.h
- targets/TARGET_NXP/TARGET_LPC176X/i2c_api.c
I developed this PR in combination with my new [I2C Slave CI shield test suite](https://github.com/mbed-ce/mbed-ce-test-tools/blob/master/CI-Shield-Tests/I2CSlaveCommsTest.cpp).  In developing the tests, I noticed that there were a few issues with LPC1768's implementation of the I2C slave HAL.  The apparent issue was that i2c_slave_read returned an incorrect number of bytes read (and seems to have been doing so for the last decade).  However, the broader issue I noticed was that the functions were not implemented in a way that matched the LPC1768 reference manual.  NXP was nice enough to provide an example state machine that implements I2CSlave, and we just ignored it!
This PR redoes both the slave read and the slave write function to actually conform to the datasheet method of doing …
> LPC1768: Rewrite I2CSlave HAL to match datasheet way of doing it

- drivers/include/drivers/PwmOut.h
- drivers/source/PwmOut.cpp
- targets/TARGET_NXP/TARGET_LPC176X/PeripheralPinMaps.h
When running CI shield tests against master, I noticed that switching the LPC1768 to static pinmaps broke the PWM test.  And it was a weird error, too -- an assertion failure with "pinmap not found for peripheral".  As it turns out, [this PR](https://github.com/ARMmbed/mbed-os/pull/11892) which added static pinmaps to PwmOut made a big mistake -- they didn't notice that PwmOut::resume() calls init() a second time, and this version of init() is hardcoded to use a regular PinName, not a static pinmap.  If you had constructed PwmOut with a static pinmap, the _pin member variable never gets initialized, so it tries to map an undefined pin for PWM output.  Bam, (likely) assertion failure.
This PR fixes the issue by storing the pinmap and the init function to use as member variables, and then …
> Fix PwmOut::resume() for static pinmap usage

- targets/TARGET_STM/TARGET_STM32F0/objects.h
- targets/TARGET_STM/TARGET_STM32F1/objects.h
- targets/TARGET_STM/TARGET_STM32F2/objects.h
- targets/TARGET_STM/TARGET_STM32F3/objects.h
- targets/TARGET_STM/TARGET_STM32F4/objects.h
- targets/TARGET_STM/TARGET_STM32F7/objects.h
- targets/TARGET_STM/TARGET_STM32G0/objects.h
- targets/TARGET_STM/TARGET_STM32G4/objects.h
- targets/TARGET_STM/TARGET_STM32H7/objects.h
- targets/TARGET_STM/TARGET_STM32L0/objects.h
- targets/TARGET_STM/TARGET_STM32L1/objects.h
- targets/TARGET_STM/TARGET_STM32L4/objects.h
- targets/TARGET_STM/TARGET_STM32L5/objects.h
- targets/TARGET_STM/TARGET_STM32U5/objects.h
- targets/TARGET_STM/TARGET_STM32WB/objects.h
- targets/TARGET_STM/TARGET_STM32WL/objects.h
- targets/TARGET_STM/device.h
- targets/TARGET_STM/pwmout_api.c
- targets/TARGET_STM/stm_pwmout_api.h
Running my new PWM test suite, I noticed that STMicro boards (STM32F429 and STM32U575) were failing a lot of cases in the PWM test.  Things were mostly OK with the frequency <=10kHz, but at 100kHz the duty cycle had excessive error, and at 1MHz the PWM signal would not even run properly -- it was stuck high or low.
To understand what was going on, I dug into the STMicro PWM HAL.  As it turns out, their procedure for selecting a PWM prescaler is... kinda sub-optimal.  Their code starts by selecting a prescaler such that one PWM count is equal to one microsecond of duty cycle -- e.g. if you ask for a period of 150us, it will try and find a prescaler such that the PWM top count is 150.  Then, if that prescaler would exceed the limit of 2^16, the code iteratively makes the top count bigger …
> STMicro: Improve PWM resolution

- targets/cmsis_mcu_descriptions.json5
- targets/targets.json5
I have been working on this PR off and on for the past month plus.  I started this project with the primary goal of finding an image for each target to display in the [target list website](https://mbed-ce.github.io/mbed-ce-test-tools/targets/), and the secondary goal of understanding each target that Mbed currently supports, who makes it, and whether it's still in production (time is ticking by, after all, and some vendors are beginning to abandon some of their Mbed-targeted boards!)
As I worked on it, I also adopted a few other goals:
- Reorganize some targets into families better so that they show on the website more cleanly.
- examples: LPC1768 and ARCH_PRO are now combined under MCU_LPC1768, K64F and SDT64B are now combined under MCU_K64F, etc
- Identify targets which are able to be …
> Reorganize targets.json5, add image URLs to all targets

- storage/blockdevice/COMPONENT_OSPIF/include/OSPIF/OSPIFBlockDevice.h
- storage/blockdevice/COMPONENT_OSPIF/source/OSPIFBlockDevice.cpp
- storage/blockdevice/COMPONENT_SD/include/SD/SDBlockDevice.h
OSPIFBlockDevice.h defined "SPI" as a global enum under the name _mode. 
Both are collision/ambiguity hazards so, using the global enum convention of the existing driver code
```
enum _mode {
SPI,
SOPI,
DOPI
};
```
has been changed to:
```
enum ospif_opi_mode {
OSPIF_OPI_MODE_SPI = 0, /* SPI mode (OPI modes disabled)*/
OSPIF_OPI_MODE_SOPI,    /* STR-OPI mode */
OSPIF_OPI_MODE_DOPI     /* DTR-OPI mode */
};
```
as well as any references in OSPIFBlockDevice.cpp
Any reference to the previous enum's in user code will result in preprocessor not defined errors.
All references to the previous enum's in user code will have to be updated with the new prefix OSPIF_OPI_MODE_
Update references in change_mode() references in https://mbed-ce.github.io/mbed-os/class_o_s_p_i_f_block_device.html) …
> fix ambiguous global enum definition for SPI in OSPIFBlockDevice driver

- connectivity/cellular/source/framework/device/CellularContext.cpp
- connectivity/cellular/tests/UNITTESTS/doubles/CellularContext_stub.cpp
- connectivity/nanostack/coap-service/test/coap-service/unittest/stub/mbedtls_stub.c
- connectivity/netsocket/CMakeLists.txt
- connectivity/netsocket/source/NetworkInterfaceDefaults.cpp
- connectivity/netsocket/tests/UNITTESTS/doubles/NetworkInterfaceDefaults_stub.cpp
- tools/python/mbed_tools/build/_internal/config/config.py
In Mbed CE, the `MBED_CONF_CELLULAR_PRESENT` define is defined only by linking to the `mbed-cellular` library (compared to old Mbed OS, where it was defined globally for the entire OS, which was... not good).  NetworkInterfaceDefaults.cpp tried to use this define, but it's likely to be undefined there, since mbed-cellular is not guaranteed to be linked to this library.
This PR moves this function to `mbed-cellular`, where MBED_CONF_CELLULAR_PRESENT is guaranteed to be defined.  This fixes the "Undefined reference to vtable for CellularInterface" link error that it was possible to get.
NOTE: Even after this PR, `mbed-cellular` may still fail to link with an undefined reference due to #304.  That issue has its own workaround, check there for details. …
> Fix CellularInterface functions never being defined

- drivers/include/drivers/SPI.h
- hal/include/hal/spi_api.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/CMakeLists.txt
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_common.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_common_arm.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_common_arm.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_dspi.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_dspi.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_dspi_edma.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_dspi_edma.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/spi_api.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/objects.h
- targets/upload_method_cfg/K64F.cmake
I tested the Freescale FRDM_K64F on the CI test shield, and found that it had a number of issues with its SPI master implementation.  This PR fixes those issues.
When the SPI word size was configured to 16 bits instead of 8, the SPI fill data would always be 0 for the upper word.  This actually is due to an issue with the underlying FSL HAL not supporting this use case.  I have put in a PR with MCUXpresso SDK for this change: https://github.com/nxp-mcuxpresso/mcux-sdk/pull/204
If you were foolish enough to call `spi_format()` after setting the frequency (jk), your SPI frequency would be reset back to 500kHz.  This is because `spi_format()` reinitializes the SPI bus but forgets to set the frequency to what it was before in that API call.  I think that the MIMXRT105x HAL had a similar …
> Lots of K64F SPI fixes

- targets/TARGET_NUVOTON/TARGET_M460/crypto/crypto-misc.cpp
This PR replaces `PlatformMutex` with `rtos::Mutex` for supporting both mbed-baremetal and mbed-os builds.
> M467: Replace PlatformMutex with rtos::Mutex

- tools/cmake/upload_methods/UploadMethodMBED.cmake
This PR tries to honor `OUTPUT_EXT` defined in `targets.json5` for **MBED** upload method flash. If it is defined, use image file with the specified extension `.<OUTPUT_EXT>` for flash, or default to `.bin`.
> Upload: Mbed: Honor OUTPUT_EXT

- targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/CMakeLists.txt
- targets/TARGET_NUVOTON/scripts/NUVOTON.py
- targets/TARGET_NUVOTON/scripts/mbed_set_post_build_nuvoton.cmake
This fixes compile errors with TF-M integration on `NU_M2354` target, including:
1. In CMake, `mbed-psa` moves out of `mbed-core`, its library type changeng to **STATIC** from **INTERFACE**. Following this modification, the platform TF-M code relying on `mbed-psa` needs to explicitly specify the dependency through `target_link_libraries()`.
2. Update post-build script to enable `OUTPUT_EXT` can be set to "bin" or "hex" in targets.json5. …
> M2354: Fix compile error with TF-M integration

- tools/cmake/upload_methods/UploadMethodOPENOCD.cmake
This PR tries to honor `OUTPUT_EXT` defined in `targets.json5` for **OPENOCD** upload method flash. If it is defined, use image file with the specified extension `.<OUTPUT_EXT>` for flash, or default to `.elf`.
> Upload: OpenOCD: Honor OUTPUT_EXT

- tools/cmake/UploadMethodManager.cmake
- tools/cmake/upload_methods/UploadMethodARDUINO_BOSSAC.cmake
- tools/cmake/upload_methods/UploadMethodJLINK.cmake
- tools/cmake/upload_methods/UploadMethodLINKSERVER.cmake
- tools/cmake/upload_methods/UploadMethodMBED.cmake
- tools/cmake/upload_methods/UploadMethodNONE.cmake
- tools/cmake/upload_methods/UploadMethodOPENOCD.cmake
- tools/cmake/upload_methods/UploadMethodPICOTOOL.cmake
- tools/cmake/upload_methods/UploadMethodPYOCD.cmake
- tools/cmake/upload_methods/UploadMethodSTLINK.cmake
- tools/cmake/upload_methods/UploadMethodSTM32CUBE.cmake
This PR changes upload method `gen_upload_target` signature from:
```
function(gen_upload_target TARGET_NAME BIN_FILE HEX_FILE)
```
To:
```
function(gen_upload_target TARGET_NAME BINARY_FILE)
```
If `OUTPUT_EXT` is undefined or defined to "bin", BINARY_FILE is .bin file, otherwise .hex file.
The update applies to all UploadMethodXxx files.
Replace #329 
------------------------------------------------------------------------------------------------------- …
> Upload:: Honor OUTPUT_EXT

- targets/TARGET_STM/TARGET_STM32WB/stm_dma_info.h
- targets/TARGET_STM/stm_dma_utils.c
- targets/TARGET_STM/stm_spi_api.c
Working on STM32H5 SPI support, I dug a bit deeper into some DMA SPI errors that we were seeing, and ended up finding and fixing a few bugs.  These were:
- in stm_dma_utils.c, some of the dest and src constants were swapped.  This had the effect of making app DMA IP v3 transfers increment the source address if you set the destination increment flag.  Oops!  Frankly I have no idea how it ever passed any tests at all like this, it should never have worked
- DMA_DEST_DATAWIDTH_WORD replaced by DMA_DEST_DATAWIDTH_BYTE in 2 places (spotted by @wdx04 in #196).  This could mess up the DMA system if you requested a 32-bit transfer
- If the word size is set to 16 or 32 bits, it turns out that the STM32 DMA HAL requires the DMA's transfer size to be set accordingly.  We were not doing this, causing …
> Fix some DMA SPI issues with DMA IP v3 and/or word size > 8 bits

- hal/include/hal/i2c_api.h
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L452xE/TARGET_NUCLEO_L452RE_P/PinNames.h
- targets/targets.json5
Made this PR when running CI shield tests on NUCLEO_L452RE_P.  Turns out that the Arduino pinmappings for this board are slightly wrong, in a way that was causing the CI tests to fail.  This PR fixes it, and also makes two other small fixes.
None
[] Covered by existing mbed-os tests …
> Fix NUCLEO_L452RE_P arduino pins

- drivers/include/drivers/SPISlave.h
- drivers/source/SPISlave.cpp
- targets/TARGET_NXP/TARGET_LPC176X/objects.h
- targets/TARGET_NXP/TARGET_LPC176X/spi_api.c
Making this PR to capture a few fixes for issues I hit while testing the new [SPI slave test suite](https://github.com/mbed-ce/mbed-ce-test-tools/blob/master/CI-Shield-Tests/SPISlaveCommsTest.cpp) for the CI test shield.
Changes are:
- Remove useless SPISlave::frequency() function.  This function does not actually work because the SPI master sets the clock frequency; the slave has no control over it.
- Add destructor to SPISlave which calls `spi_free()`.  This makes sure that resources used by the SPI slave can actually be cleaned up like they are for an SPI master instance.
- LPC1768: unmap SPI pins in spi_free().  This is so that test cases will pass that involve remapping SPI pins as NC.
- I realize that it's a bit unclear in many cases whether Mbed HALs are supposed to unmap pins in …
> Fixes for SPI slave implementation

- targets/upload_method_cfg/LPC1768.cmake
- tools/cmake/upload_methods/FindOpenOCD.cmake
- tools/cmake/upload_methods/UploadMethodOPENOCD.cmake
Quick update to the OpenOCD upload method to allow the configuration to specify a valid range of OpenOCD versions that will work.
This will allow @ccli8 to make sure that Nuvoton upload methods only work with Nuvoton OpenOCD
None
Updated the upload method page: https://github.com/mbed-ce/mbed-os/wiki/Upload-Methods
[] No Tests required for …
> Allow upload method configs to specify an OpenOCD version range

- targets/TARGET_NUVOTON/README.md
- targets/upload_method_cfg/NUMAKER_IOT_M252.cmake
- targets/upload_method_cfg/NUMAKER_IOT_M263A.cmake
- targets/upload_method_cfg/NUMAKER_IOT_M467.cmake
- targets/upload_method_cfg/NUMAKER_IOT_M487.cmake
- targets/upload_method_cfg/NUMAKER_PFM_M453.cmake
- targets/upload_method_cfg/NUMAKER_PFM_M487.cmake
- targets/upload_method_cfg/NUMAKER_PFM_NANO130.cmake
- targets/upload_method_cfg/NUMAKER_PFM_NUC472.cmake
- targets/upload_method_cfg/NU_M2354.cmake
- targets/upload_method_cfg/openocd_cfgs/numicro_m0.cfg
- targets/upload_method_cfg/openocd_cfgs/numicro_m23.cfg
- targets/upload_method_cfg/openocd_cfgs/numicro_m4.cfg
This supports upload method for Nuvoton targets, including:
- NUMAKER_PFM_NANO130
- NUMAKER_PFM_NUC472
- NUMAKER_PFM_M453
- NUMAKER_PFM_M487
- NUMAKER_IOT_M487
- NUMAKER_IOT_M467
- NUMAKER_IOT_M252
- NUMAKER_IOT_M263A
- NU_M2354
> Upload: Support Nuvoton targets

- tools/cmake/mbed_target_functions.cmake
This fixes linker script is incorrectly selected for bare-metal profile. `mbed-os` and `mbed-baremetal` library targets [both are created](https://github.com/mbed-ce/mbed-os/blob/b352953f8680494505cc14ea1b4e19f3b7c9f975/CMakeLists.txt#L284-L285), so we cannot use `if(TARGET mbed-os)` or `if(TARGET mbed-baremetal)` to determine which one the application target links to. Instead, determine by checking application target's `LINK_LIBRARIES` property. …
> Fix linker script incorrectly selected for bare-metal profile

- connectivity/lwipstack/source/LWIPInterface.cpp
- connectivity/netsocket/include/netsocket/EMACInterface.h
- connectivity/netsocket/include/netsocket/NetworkInterface.h
- connectivity/netsocket/include/netsocket/nsapi_types.h
- connectivity/netsocket/source/EMACInterface.cpp
- connectivity/netsocket/source/NetworkInterface.cpp
- connectivity/netsocket/tests/UNITTESTS/doubles/NetworkInterface_stub.cpp
- connectivity/netsocket/tests/UNITTESTS/netsocket/NetworkInterface/test_NetworkInterface.cpp
Add support for hostname request in lwIP interface.
There is a discussion about this functionality here: [How to set device network hostname on MBED OS 6?](https://forums.mbed.com/t/how-to-set-device-network-hostname-on-mbed-os-6/10086/8)
[] Covered by existing mbed-os tests (Greentea …
> Add support for hostname request in lwIP interface

- connectivity/drivers/mbedtls/TARGET_NUVOTON/TARGET_M460/CMakeLists.txt
For Nuvoton M467, this fixes mbedtls H/W acceleration build error on migration to Mbed CE.
> M467: Fix mbedtls H/W acceleration build error

- tools/cmake/upload_methods/UploadMethodPYOCD.cmake
PyOCD debug restart can be failed without this somehow. It appears the device under debug must be halted after `MBED_UPLOAD_RESTART_COMMANDS`, but this is broken. Change to `monitor reset halt` to fix it.
NOTE: The above issue is reproduced on Nuvoton's NUMAKER_IOT_M467 target.
> Upload: Fix GDB restart command for pyOCD

- targets/TARGET_NUVOTON/TARGET_M460/gpio_irq_api.c
This fixes missing `gpio_base` on invoking `GPIO_SET_DEBOUNCE_TIME()` for Nuvoton's NUMAKER_IOT_M467 target.
> M467: Fix invoking GPIO_SET_DEBOUNCE_TIME

- targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/CMakeLists.txt
- targets/targets.json5
Fix for build errors on STM32H7Ax:
- Typo in targets JSON so clock settings weren't being applied
- CMake looking for nonexistent system_clock.c
Tested locally, it compiles now! …
> Fix STM32H7Ax build

- connectivity/drivers/802.15.4_RF/CMakeLists.txt
- connectivity/nanostack/mbed-mesh-api/CMakeLists.txt
- connectivity/netsocket/CMakeLists.txt
This is somewhat similar to the fix I had to do for wifi devices a while back.  If the default network device is MESH, we need to ensure that Nanostack and the mesh networking drivers are linked in with `mbed-netsocket`.  This also fixes some CMake build issues for nanostack and the mesh networking drivers.
[] No Tests required for this change …
> Fix build for devices with MESH as the default network type

- targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/CMakeLists.txt
- targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_NUCLEO_H745ZI_Q/CMakeLists.txt
The CMake build files for NUCLEO_H745ZI_Q were quite messed up -- it never added the subdirectory, and some of the target names had typos so it couldn't actually build properly.  This fixes the buildfile issues and condenses down the CMake targets to remove duplicated code.
[] Covered …
> Fix messed up CMake targets for NUCLEO_H745ZI_Q

- targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_ARM/LPC1768.ld
- tools/cmake/mbed_set_linker_script.cmake
- tools/cmake/mbed_target_functions.cmake
- tools/python/memap/memap.py
I noticed that for targets that had stack fill up until the end of a memory bank, the new memap version was doing some weird stuff:
- It would print a warning about the symbol going outside of the memory bank,
- And, that warning would have the wrong name, it would call out a previous symbol name rather than saying it was `*fill*` that did it 
Turns out there was an off by 1 error in the check for whether a symbol went outside a memory bank, and an issue with the regex that detected the names of input sections.
[] Major update …
> Fix off-by-1 error in memap's symbol-contained-in-memory-bank check, clean up some linker script stuff

- targets/cmsis_mcu_descriptions.json5
- targets/targets.json5
MIMXRT1170_EVK greentea build was failing because there were no memory banks defined for MIMXRT1176.  This was actually pretty tough to figure out, even for me who has experience with the MIMRT family of chips, because the CMSIS pack memory description is not too helpful and the datasheet is confusing AF.  Finally had to check what the default configuration was in MCUXpresso IDE and that helped a lot.
MIMXRT1176 MCU now has memory bank information.
See comments in file
[] Major update (Breaking change E.g. Return code change / API …
> Add MIMXRT1176 MCU description and fix build failure

- connectivity/FEATURE_BLE/source/generic/GattClientImpl.cpp
- connectivity/netsocket/tests/TESTS/netsocket/tls/tlssocket_cert_in_filesystem.cpp
- connectivity/netsocket/tests/TESTS/netsocket/udp/main.cpp
- drivers/tests/TESTS/mbed_drivers/reset_reason/main.cpp
- drivers/usb/include/usb/internal/USBDevice.h
- drivers/usb/source/USBDevice.cpp
- drivers/usb/tests/TESTS/usb_device/msd/main.cpp
- hal/tests/TESTS/mbed_hal/ospi/main.cpp
- hal/tests/TESTS/mbed_hal/sleep_manager_racecondition/main.cpp
- hal/tests/TESTS/mbed_hal/ticker/main.cpp
- hal/tests/TESTS/pin_names/arduino_uno/main.cpp
- platform/tests/TESTS/mbed_functional/callback/main.cpp
- platform/tests/TESTS/mbed_micro/cpp/main.cpp
- platform/tests/TESTS/mbed_platform/FileHandle/main.cpp
- platform/tests/TESTS/mbed_platform/error_handling/main.cpp
- platform/tests/TESTS/mbed_platform/minimal-printf/compliance/CMakeLists.txt
- platform/tests/TESTS/mbed_platform/minimal-printf/compliance/main.cpp
- platform/tests/TESTS/mbed_platform/wait_ns/main.cpp
- rtos/tests/TESTS/mbed_rtos/heap_and_stack/main.cpp
- rtos/tests/TESTS/mbed_rtos/malloc/main.cpp
- rtos/tests/TESTS/mbed_rtos/mutex/main.cpp
- rtos/tests/TESTS/mbed_rtos/signals/main.cpp
- rtos/tests/TESTS/mbed_rtos/threads/main.cpp
- tools/cmake/toolchains/GCC_ARM.cmake
- tools/python/memap/memap.py
Ever since I've started on Mbed CE, there have been ludicrous amounts of warnings every time the greentea tests are compiled.  The vast majority of these are due to tests using deprecated API, especially legacy RTOS functions that don't use chrono types.  This PR fixes at least 90% of these warnings, so the greentea build is now a much more warning-free experience.  There are still a few here and there but it's a lot better now at least.
Someday I want to fix all of the warnings and then make the CI builds use -Werror but... not today.
Way less warnings in Greentea test builds
None
[] Feature …
> Fix lots of Greentea test warnings

- .github/workflows/test_building_multiple_executables.yml
- targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/CMakeLists.txt
- targets/TARGET_Cypress/scripts/PSOC6.py
- targets/TARGET_Cypress/scripts/mbed_set_post_build_cypress.cmake
- tools/requirements.txt
This PR fixes a couple issues preventing the build of the CYTFM_064B0S2_4343W target:
- Missing dependency on `cysecuretools` in requirements.txt prevented the post build script from running
- The post build script was trying to create and sign `tfm_s.hex` in the build dir for every target that compiled, so if multiple targets built in parallel, the build would fail with a corrupt file error.
- Missing dependency on `mbed-psa` for the MCU target, added this the same as for the Nuvoton target
[] Major update (Breaking change E.g. …
> Fix build of CYTFM_064B0S2_4343W

- .github/workflows/greentea_cmake.yml
- .github/workflows/test_building_multiple_executables.yml
- connectivity/FEATURE_BLE/source/cordio/TESTS/cordio_hci/transport/CMakeLists.txt
- connectivity/drivers/emac/TARGET_RENESAS_EMAC/TARGET_RZ_A1XX/CMakeLists.txt
- connectivity/drivers/emac/TARGET_STM/stm32xx_emac.cpp
- targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/CMakeLists.txt
- targets/TARGET_Cypress/scripts/PSOC6.py
- targets/TARGET_Cypress/scripts/mbed_set_post_build_cypress.cmake
- targets/TARGET_Maxim/TARGET_MAX32670/CMakeLists.txt
- targets/TARGET_Maxim/TARGET_MAX32670/Libraries/PeriphDrivers/Source/SYS/sys_me15.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/device/cmsis_nvic.h
- targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/PinNames.h
- targets/TARGET_STM/stm_dma_utils.c
- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG11/device/em_device.h
- tools/requirements.txt
I feel like we have had lots of issues where someone (often me) changes a file for target X and that causes a build failure for target Y.  I think we should put an end to that -- things like this are basically why CI was invented!  Will this cause us to get rate limited by Github Actions?  No idea!  But let's find out!
Submitting a pull request will now cause Mbed to be compiled for every major target family. …
> Build all target families in a CI job

- targets/targets.json5
Noticed that the website generator CI job was printing some warnings about overriding some attributes that didn't exist and then dying with a foreign key error.  Oops!
Turns out that I kinda messed up in my attempt to refactor these STM32H7 targets.  Not only were there some typos, which weren't caught by the testing I did but were caught by the website generator, but also the inheritance order is backwards from how I expected it: the first target in the list of parent targets gets the highest "priority" and can override the attributes from the other targets.  Interestingly, this [is actually documented](https://github.com/mbed-ce/mbed-os/blob/master/tools/python/mbed_tools/targets/_internal/targets_json_parsers/overriding_attribute_parser.py#L61) in the code if you know where to look.
To …
> Fix STM32H7 dual core inheritance again

- connectivity/FEATURE_BLE/source/cordio/stack_adaptation/hci_tr.c
Based on
https://github.com/ARMmbed/mbed-os/pull/15474
Summary of changes
Set the stateRx variable to HCI_RX_STATE_IDLE when an invalid HCI packet type is detected, to prevent overflow in the hdrRx buffer.
Impact of changes
Migration actions required
Documentation
Pull request type
Test results
> Fix the vulnerability of mbed-os #15462 issue

- targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/CMakeLists.txt
- targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/README.md
- targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/signing_key/nuvoton_m2354-root-rsa-3072.md
This fixes some minor issues of Nuvoton's M2354 target, including:
1. TF-M import document
2. Pre-create of cmake target `mbed-m2354-tfm` for use in `custom_targets`.
> M2354: Fix some TF-M minor issues

- connectivity/drivers/wifi/COMPONENT_ESPRESSIF_ESP8266/CMakeLists.txt
- connectivity/drivers/wifi/COMPONENT_ESPRESSIF_ESP8266/ESP8266Interface.cpp
- connectivity/drivers/wifi/COMPONENT_WHD/whd_mac/CMakeLists.txt
- connectivity/drivers/wifi/COMPONENT_WHD/whd_mac/interface/whd_interface.cpp
- connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/CMakeLists.txt
- connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/EMW3080BInterface.cpp
- connectivity/drivers/wifi/TARGET_WICED/CMakeLists.txt
- connectivity/drivers/wifi/TARGET_WICED/wiced_interface/default_wifi_interface.cpp
- connectivity/netsocket/CMakeLists.txt
This fixes WiFi cannot configure as default network interface, e.g. `"esp8266.provide-default": true`. This configuration requires support for weak symbol override. Object files archived in static library don't always participate in linking, dependent on linker and link order. The steps below introduced in this PR pull in the override object file anyway even though it comes from static library:
1. Add e.g. GCC linker option `--undefined=<LINK_FOO>`
2. Add `<LINK_FOO>` function with `extern "C"` in override source file
See: https://stackoverflow.com/questions/42588983/what-does-the-gnu-ld-undefined-option-do
**NOTE**: This provides an alternative to #373 and would be more reasonable.
------------------------------------------------------------------------------------------------------------ …
> Fix wifi cannot configure as default network interface

- connectivity/libraries/nanostack-libservice/CMakeLists.txt
nanostack-libservice involves two parts: common (e.g. [libip4string](https://github.com/mbed-ce/mbed-os/tree/master/connectivity/libraries/nanostack-libservice/source/libip4string)) and nanostack-specific (e.g. [nvmHelper](https://github.com/mbed-ce/mbed-os/tree/master/connectivity/libraries/nanostack-libservice/source/nvmHelper)). For nanostack-specific, it needs to link [nanostack hal](https://github.com/mbed-ce/mbed-os/tree/master/connectivity/nanostack/nanostack-hal-mbed-cmsis-rtos) and will pull in 200+ nanostack files for compile. This is unnecessary for common only application e.g. lwipstack. To fix this, the following strategy is applied for nanostack-libservice cmake listfile:
1.  For compiling nanostack-specific, it doesn't rely on nanostack hal because its needed header file …
> Decrease compile time with nanostack-libservice

- targets/TARGET_STM/can_api.c
- tools/cmake/app.cmake
Noticed while working on the custom targets example that if you pass a relative path to CUSTOM_UPLOAD_CFG_PATH, it errors out, because EXISTS in CMake only works with absolute paths (seriously this is such a common foot-gun and they still have not fixed it).
Also noticed a compiler warning coming from the STM32 CAN code.  It appears that there was some unintentional behavior happening because the `<` operator has higher precedence than `&`, so the comparison was happening before the mask!  It looks like they were trying to get the length from the DLC field, so I updated the code to use a proper register definition and parentheses as needed.
None
[X] Patch update (Bug fix / …
> Fix relative paths to custom upload method file, fix incorrect CAN length on STMicro

- tools/python/mbed_tools/build/_internal/config/config.py
`memory_bank_config` can be defined in targets.json or custom_targets.json per-target, but cannot by application. This enables this override by adding `target.memory_bank_config` config in `target_overrides` section of mbed_app.json as usual.
Fix #370.
> Support override of memory_bank_config in mbed_app.json

- connectivity/FEATURE_BLE/libraries/cordio_stack/wsf/sources/port/baremetal/wsf_msg.c
- connectivity/FEATURE_BLE/source/cordio/stack_adaptation/hci_tr.c
`hciTrSerialRxIncoming` parses incoming hci packets. In doing so, it dynamically determines the length of the packet body. For the case of `HCI_ACL_TYPE` this is done by reading 2 bytes from the packet header.
https://github.com/mbed-ce/mbed-os/blob/54e8693ef4ff7e025018094f290a1d5cf380941f/connectivity/FEATURE_BLE/source/cordio/stack_adaptation/hci_tr.c#L182-L195
A buffer is then allocated to hold the packet, the length of which is determined by the sum of this 16bit integer and the length of the packet header.
https://github.com/mbed-ce/mbed-os/blob/54e8693ef4ff7e025018094f290a1d5cf380941f/connectivity/FEATURE_BLE/source/cordio/stack_adaptation/hci_tr.c#L197-L201
The final buffer size is also increased by `WsfMsgAlloc`, which adds the size of one `wsfMsg_t`. …
> Cordio BLE: Fix integer overflows (CVE-2024-48983)

- connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/hci/dual_chip/hci_evt.c
`hciEvtProcessLeExtAdvReport` parses lists of hci reports. In doing so, it dynamically determines the length of the list by reading a byte from the input buffer.
https://github.com/mbed-ce/mbed-os/blob/54e8693ef4ff7e025018094f290a1d5cf380941f/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/hci/dual_chip/hci_evt.c#L1317
The function then steps through the input buffer and reads the length of all the individual reports in order to find the largest one. It then allocates a buffer that is capable of holding the largest report. 
https://github.com/mbed-ce/mbed-os/blob/54e8693ef4ff7e025018094f290a1d5cf380941f/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/hci/dual_chip/hci_evt.c#L1331-L1343
However, no check is done to ensure that those other reports are …
> Cordio BLE: fix OOB read in event processing (CVE-2024-48984)

- connectivity/FEATURE_BLE/source/cordio/stack_adaptation/hci_tr.c
`hciTrSerialRxIncoming` parses incoming hci packets. It takes two bytes from the packet header and tries to allocate a buffer based on the packet size contained in those bytes. There is no logic to account for the case of an allocate failing. If `WSF_ASSERT` is not enabled (it isn't by default), the packet isn't dropped either.
- https://github.com/mbed-ce/mbed-os/blob/54e8693ef4ff7e025018094f290a1d5cf380941f/connectivity/FEATURE_BLE/source/cordio/stack_adaptation/hci_tr.c#L200
This means that the function will stay in it's `HCI_RX_STATE_HEADER` state for longer than intended. Because every iteration of the loop writes another byte to `hdrRx` and the intended exit condition for this state has been passed, it will continue writing to `hdrRx` past it's bounds, causing a buffer overflow. …
> Codrio BLE: ignore packet if data allocation fails (CVE-2024-48985)

- connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/hci/dual_chip/hci_evt.c
`hciEvtProcessMsg` parses incoming hci command packets. In doing so, it dynamically determines the length of the packet body by reading a byte from the packet header.
- https://github.com/mbed-ce/mbed-os/blob/54e8693ef4ff7e025018094f290a1d5cf380941f/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/hci/dual_chip/hci_evt.c#L2748
Then, `hciEvtProcessCmdCmpl` is called. A buffer is allocated to hold the packet, the length of which is determined by the sum of this 8-bit integer and the length of a structure to hold some metadata but without 3 bytes that are assumed to exist and have already been read.
- https://github.com/mbed-ce/mbed-os/blob/54e8693ef4ff7e025018094f290a1d5cf380941f/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/hci/dual_chip/hci_evt.c#L2685-L2 …
> Cordio BLE: Fix two integer overflows (CVE-2024-48982)

- tools/cmake/UploadMethodManager.cmake
The purpose of `mbed_adjust_upload_debug_commands()` is to adjust first version of `MBED_UPLOAD_LAUNCH_COMMANDS`. For multiple executalbe cmake targets, `MBED_UPLOAD_LAUNCH_COMMANDS` becomes not fresh and may cause error. To overcome this, one new cmake cache variable `MBED_UPLOAD_LAUNCH_COMMANDS_BAK` is introduced to save first version of `MBED_UPLOAD_LAUNCH_COMMANDS`.
Fix #383
----------------------------------------------------------------------------- …
> Upload: Fix mbed_adjust_upload_debug_commands for multiple targets

- connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/hci/dual_chip/hci_evt.c
`hciEvtProcessMsg` parses incoming hci command packets. In doing so, it dynamically determines the length of the packet body and the event type by reading 2 bytes from the packet header.
- https://github.com/mbed-ce/mbed-os/blob/54e8693ef4ff7e025018094f290a1d5cf380941f/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/hci/dual_chip/hci_evt.c#L2747-L2748
Depending on the event type, it will set a callback flag. If this flag is set later, it allocates a buffer with a semi-constant length determined by an event type to buffer length lookup table.
It then copies bytes into the allocated buffer but uses the packet supplied length value to copy them.
- https://github.com/mbed-ce/mbed-os/blob/54e8693ef4ff7e025018094f290a1d5cf380941f/connectivity/FEATURE_BLE/libraries/cordio_stack/b …
> Cordio BLE: ignore messages with overlong headers (CVE-2024-48986)

- targets/TARGET_RASPBERRYPI/TARGET_RP2040/TOOLCHAIN_GCC_ARM/memmap_default_mbed.ld
- targets/TARGET_RASPBERRYPI/TARGET_RP2040/cmsis_nvic.h
- targets/TARGET_RASPBERRYPI/TARGET_RP2040/flash_api.c
- targets/TARGET_RASPBERRYPI/TARGET_RP2040/rtc_api.c
- targets/targets.json5
I noticed that RPi Pico got broken a while back due to the upload method changes, because it does not have a flash bank defined, so the upload methods don't have a location to upload to.  Funnily enough I actually did write such a flash bank definition in the memory banks example on the page, but never actually put it into the code X_X.
This PR updates the RP2040 target to:
- Have a defined QSPI flash bank, whose size can be configured via `memory_banks` and `memory_bank_config`
- Generally custom target creators should set the physical size of the flash in `memory_banks` and the configured area for the Mbed application in `memory_bank_config`, because the `memory_banks` definition is now used for the flash programming HAL
- Use the configured flash and RAM sizes in the linker script, …
> Update RP2040 target to use flash memory bank

- tools/python/mbed_tools/cli/cmsis_mcu_descr.py
This PR will update cmsis_mcu_descr.py to be able to operate also for custom targets.
The script was able to scan only targets.json5 file and potential existence of custom_targets.json5 was ignored.
Well, no more.
N/A
N/A
[x] No Tests required for this change (E.g docs only update)
[] …
> Update cmsis_mcu_descr.py for custom targets

- cmsis/device/rtos/TOOLCHAIN_GCC_ARM/mbed_boot_gcc_arm.c
- cmsis/device/rtos/include/mbed_boot.h
- cmsis/device/rtos/source/mbed_boot.c
- platform/source/mbed_retarget.cpp
- platform/source/mbed_sdk_boot.c
- rtos/tests/TESTS/mbed_rtos/heap_and_stack/main.cpp
- targets/TARGET_STM/TARGET_STM32H7/linker_scripts/STM32H743_STM32H72x_FAMILIES/STM32H743_H72x.ld
- targets/TARGET_STM/TARGET_STM32H7/linker_scripts/STM32H745_47_FAMILY/CM4/STM32H745_H747_CM4.ld
- targets/TARGET_STM/TARGET_STM32H7/linker_scripts/STM32H745_47_FAMILY/CM7/STM32H745_H747_CM7.ld
- targets/TARGET_STM/TARGET_STM32H7/linker_scripts/STM32H7Ax_FAMILY/STM32H7Ax.ld
- targets/targets.json5
The change that I made a month or two ago to use DTCM as the default heap on STM32H7 has caused some unforseen consequences.  Basically, the DMA controller cannot access anything in DTCM in any shape or form, so using SDIO, Ethernet, or DMA SPI with heap-allocated buffers will cause a crash or unintended behavior.
This PR updates the STM32H7 linker scripts (soooo glad there are only 4 of them now!) to use main SRAM as heap 0 and SRAM_D2/SRAM_AXI as heap.  This way, we still can take advantage of two of the memory banks for heap size, but we don't have to deal with the issues caused by DTCM.  DTCM provides a big performance boost, make no mistake, but I think it's best left as a power user only option.
I also made one other change in this, which is that until now, targets which implemented …
> STM32H7: Don't use DTCM memory for heap

- connectivity/cellular/CMakeLists.txt
- connectivity/drivers/cellular/Altair/COMPONENT_ALTAIR_ALT1250/PPP/ALT1250_PPP.cpp
- connectivity/drivers/cellular/Altair/COMPONENT_ALTAIR_ALT1250/PPP/CMakeLists.txt
- connectivity/drivers/cellular/COMPONENT_STMOD_CELLULAR/CMakeLists.txt
- connectivity/drivers/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.cpp
- connectivity/drivers/cellular/GEMALTO/COMPONENT_GEMALTO_CINTERION/CMakeLists.txt
- connectivity/drivers/cellular/GEMALTO/COMPONENT_GEMALTO_CINTERION/GEMALTO_CINTERION.cpp
- connectivity/drivers/cellular/GENERIC/COMPONENT_GENERIC_AT3GPP/CMakeLists.txt
- connectivity/drivers/cellular/GENERIC/COMPONENT_GENERIC_AT3GPP/GENERIC_AT3GPP.cpp
- connectivity/drivers/cellular/MultiTech/DragonflyNano/COMPONENT_MULTITECH_DRAGONFLY_NANO_CELLULAR/CMakeLists.txt
- connectivity/drivers/cellular/MultiTech/DragonflyNano/COMPONENT_MULTITECH_DRAGONFLY_NANO_CELLULAR/SARA4_PPP.cpp
- connectivity/drivers/cellular/RiotMicro/COMPONENT_RIOTMICRO_RM1000/CMakeLists.txt
- connectivity/drivers/cellular/RiotMicro/COMPONENT_RIOTMICRO_RM1000/RM1000_AT.cpp
- connectivity/drivers/cellular/TELIT/COMPONENT_TELIT_HE910/CMakeLists.txt
- connectivity/drivers/cellular/TELIT/COMPONENT_TELIT_HE910/TELIT_HE910.cpp
- connectivity/drivers/cellular/TELIT/COMPONENT_TELIT_ME310/CMakeLists.txt
- connectivity/drivers/cellular/TELIT/COMPONENT_TELIT_ME310/TELIT_ME310.cpp
- connectivity/drivers/cellular/TELIT/COMPONENT_TELIT_ME910/CMakeLists.txt
- connectivity/drivers/cellular/TELIT/COMPONENT_TELIT_ME910/TELIT_ME910.cpp
- connectivity/netsocket/source/NetworkInterfaceDefaults.cpp
This fixes cellular build issues, including:
1. Add back weak `CellularInterface::get_default_instance` so that cellular driver can provide default just overriding `CellularDevice::get_default_instance`.
2. Like #377, fix `CellularDevice::get_default_instance` coming from static library cannot participate in linking and so cannot override.
3. Fix `ThisThread::sleep_until` link error, this is caused by [mismatch on `MBED_CONF_RTOS_PRESENT` defined or not between executable and `mbed-cellular` targets](https://github.com/mbed-ce/mbed-os/blob/2564b2c1bfc78ef8425cc81de34f3cb0d3f90cc4/rtos/include/rtos/Kernel.h#L79-L86).
[X] Patch update (Bug fix / Target update / Docs update / Test …
> Fix build issues with cellular

- connectivity/mbedtls/CMakeLists.txt
This reflects [Mbed OS's mbedtls PSA support](https://github.com/mbed-ce/mbed-os/blob/df28d42a770e0da7c65f156c72e22ab876171b4b/connectivity/mbedtls/include/mbedtls/config.h#L3899-L3902) and fixes mbedtls link error with `mbed-psa` missing. `mbed-psa` provides one mbed psa implementation which mbedtls needs to link. For example, `mbedtls_hardware_poll `(located in [mbedtls mbed_trng.cpp](https://github.com/mbed-ce/mbed-os/blob/master/connectivity/mbedtls/platform/src/mbed_trng.cpp)) invokes [trng_init](https://github.com/mbed-ce/mbed-os/blob/df28d42a770e0da7c65f156c72e22ab876171b4b/platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/src/psa_hrng.c#L22-L25) and friends which are implemented in [mbed-psa psa_hrng.c](https://github.com/mbed-ce/mbed-os/blob/master/platform/FEATURE_EXPERIMENTAL_API/FE …
> mbedtls: fix mbed-psa link missing

- tools/cmake/UploadMethodManager.cmake
- tools/cmake/upload_methods/FindLinkServer.cmake
- tools/cmake/upload_methods/UploadMethodARDUINO_BOSSAC.cmake
- tools/cmake/upload_methods/UploadMethodJLINK.cmake
- tools/cmake/upload_methods/UploadMethodLINKSERVER.cmake
- tools/cmake/upload_methods/UploadMethodMBED.cmake
- tools/cmake/upload_methods/UploadMethodOPENOCD.cmake
- tools/cmake/upload_methods/UploadMethodPICOTOOL.cmake
- tools/cmake/upload_methods/UploadMethodPYOCD.cmake
- tools/cmake/upload_methods/UploadMethodSTLINK.cmake
- tools/cmake/upload_methods/UploadMethodSTM32CUBE.cmake
As part of mcuboot support, we need a way to generate upload targets for things that aren't actual CMake build targets.  We can alllllmost do that with the existing code, but not quite!  Needed to move the add_dependencies() call to the upper level function.
I also noticed a bug while working on this: if old versions of LinkServer are given a hex file, they just treat it as a bin file and _flash the ASCII text of the hex file into memory_!!!!  It's extremely confusing when it happens, and I added a check to catch this situation.
None …
> Tweak upload method dependencies to be specified at a higher level, add LinkServer version check

- tools/cmake/mbed_set_linker_script.cmake
Fix dependency error with custom linker scripts.  Back in #362 I added the LINK_DEPENDS property so that executables would be rebuilt if the linker script changed.  However, it caused a circular dependency error with custom linker scripts, because the linker script was expected to exist before the link command (which generated the linker script) could be run!  This PR fixes this by putting the dependency on the raw file instead of the preprocessed one.
None
[] Major update (Breaking change E.g. Return code change / API behaviour …
> Fix CMake dependency error with custom linker scripts

- connectivity/drivers/emac/TARGET_STM/mbed_lib.json
- connectivity/drivers/emac/TARGET_STM/stm32xx_emac.cpp
- connectivity/drivers/emac/TARGET_STM/stm32xx_emac.h
This MR adds multicast filtering support to all STM32 MCUs that support Ethernet.  It's an offshoot from my ongoing branch to rewrite the STM32 EMAC code (which is making progress, but slooooowly).
STM32 MCUs have both a "perfect" multicast filter and a hash filter.  The perfect filter can match up to 3 mcast addresses exactly, while the hash filter matches mcast MAC addresses using a 64-entry hash table.   The hash table method is obviously limited -- if you subscribe to, say, 32 MAC addresses using the hash table, you will have a 50% false positive rate for all other MAC addresses.  So, this driver uses the perfect filter for the first 3 MAC addresses, then the hash table for any additional MACs.
By default, 8 addresses are supported, but this can be increased via the …
> Add multicast filter support to STM32 EMAC

- platform/mbed_lib.json
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_GCC_ARM/MK64FN1M0xxx12.ld
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/TARGET_1050_EVK/xip/evkbimxrt1050_flexspi_nor_config.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/TARGET_1060_EVK/xip/evkbmimxrt1060_flexspi_nor_config.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/flash_api.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/flash_defines.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/fsl_flexspi_nor_boot.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_EVK/mimxrt_memory_info.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_TEENSY_4X/TARGET_TEENSY_40/mimxrt_memory_info.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/TARGET_TEENSY_4X/TARGET_TEENSY_41/mimxrt_memory_info.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/device/TOOLCHAIN_GCC_ARM/MIMXRT1052xxxxx.ld
- targets/targets.json5
This PR upgrades the MIMXRT105x/6x linker script to use memory banks instead of the hand-written header file that it had been using.  This enables bootloader support on the MIMXRT106x, and I also took the chance to enable crash data RAM on it.
Unfortunately, while testing this change, I ran into constant failures on the heap fill test (which I don't think had been reactivated until a couple months ago, so it never got run on this target before).  It showed that there was corruption happening in the external 256MB SDRAM: bytes received didn't always match bytes written back.
For now, I didn't have a ton of time to dig into this, after half an hour of messing around I kinda had to keep moving.  So, I had to disable the SDRAM for now to restore stable operation of the chip.  Thankfully it …
> MIMXRT105x: upgrade linker script to use memory banks, disable SRAM

- connectivity/drivers/emac/TARGET_STM/stm32xx_emac.cpp
- hal/tests/TESTS/mbed_hal/mpu/main.cpp
Did some checking into *finally* fixing this annoying test failure that has been happening for years. The hal-mpu stack fault test has been dying on most MCUs 100% of the time, and it wasn't super obvious why.
When debugging the test, I noticed that it was dying because it was executing a garbage instruction (NOT because it was executing from RAM -- that's an intended part of the test). Why was this happening? Well, stepping through the disassembly of `mpu_fault_test_stack()`, it looked like the compiler had reordered the instructions, and was executing line 141 before line 147! So it was executing the RAM instruction before said instruction had been initialized with a value.
Why was that happening? Well, I think that the cast that this test does breaks aliasing rules in C++ -- it's …
> Fix HAL MPU test on Cortex M7 CPUs

- targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/tfm_ns_interface.c
- targets/targets.json5
For Nuvoton M2354 target, this adds support for baremetal profiile.
> M2354: Support baremetal profile

- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/CMakeLists.txt
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/mbed_overrides.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT105x/sleep.c
- targets/targets.json5
Per recent discussion, this disables deep sleep by default on the MIMXRT1060_EVK.
Updated the [info page](https://github.com/mbed-ce/mbed-os/wiki/MCU-Info-Page:-MIMXRT105x-and-106x)
[X] Tests / results supplied as part of this …
> MIMXRT1060_EVK: Disable deep sleep by default

- cmsis/device/rtos/TOOLCHAIN_GCC_ARM/mbed_boot_gcc_arm.c
- cmsis/device/rtos/include/mbed_boot.h
- platform/source/mbed_alloc_wrappers.cpp
- platform/source/mbed_retarget.cpp
- platform/source/mbed_sdk_boot.c
This is a fix for the field heap_stats.reserved_size in the mbed heap statistics. With split heap, the heap can contain two heap areas. In this case, mbed_heap_size changes to be the 2nd heap, and mbed_heap_size_0 will become the first heap part.
The heap statistics did took that change into account, and always used mbed_heap_size for the total heap size.
This PR adds a variable mbed_heap_size_total to reflect the total size, regardless if one or two heaps are used.
Heap functions are declared as weak, so a custom implementation could be used for even more heap areas or heap in external SDRAM. In this case, the variable mbed_heap_size_total must be calculated in software_init_hook() in mbed_boot_gcc_arm.c for a correct output in the heap statistics. …
> Fix heap get for split heap

- CMakeLists.txt
- TESTS/configs/greentea_baremetal.json5
- connectivity/cellular/CMakeLists.txt
- connectivity/drivers/802.15.4_RF/CMakeLists.txt
- connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_2/CMakeLists.txt
- connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_MS/CMakeLists.txt
- connectivity/drivers/emac/CMakeLists.txt
- connectivity/drivers/wifi/CMakeLists.txt
- connectivity/drivers/wifi/COMPONENT_WHD/whd-bsp-integration/CMakeLists.txt
- connectivity/libraries/ppp/CMakeLists.txt
- connectivity/lwipstack/CMakeLists.txt
- connectivity/nanostack/mbed-mesh-api/CMakeLists.txt
- connectivity/nanostack/nanostack-hal-mbed-cmsis-rtos/CMakeLists.txt
- connectivity/netsocket/tests/emac_test_utils/CMakeLists.txt
- drivers/usb/CMakeLists.txt
- targets/targets.json5
- tools/cmake/mbed_greentea.cmake
- tools/cmake/mbed_target_functions.cmake
This PR tries to address #407, including:
1.  Provide one approach to address cmake link mess with `mbed-core-flags`/
`mbed-rtos-flags` whose links or not depends on selected application profile,
`full` or `bare-metal`.
1.  Add target config option `application-profile` for application to
select which application profile to use. Applications are responsible
for make this target config option consitent with link selection of
mbed-os/mbed-baremetal.
2.  Add cmake interface library `mbed-application-profile-flags`. It is to
substitute for mbed-core-flags/mbed-rtos-flags. Library camke targets
should change to link this one to build upon correct application profile
selection.
2.  All in-tree library targets link `mbed-application-profile-flags` instead of `mbed-core-flags`/`mbed-rtos-flags` …
> Fix application profile link mess

- .gitignore
- connectivity/lwipstack/lwip-sys/arch/lwip_sys_arch.c
- connectivity/netsocket/tests/TESTS/netsocket/tcp/tcpsocket_recv_100k.cpp
- connectivity/netsocket/tests/emac_test_utils/EmacTestMemoryManager.cpp
- drivers/tests/TESTS/mbed_drivers/flashiap/main.cpp
- targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_ARM/LPC1768.ld
- targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_ARM/startup_LPC17xx.S
- targets/TARGET_NXP/TARGET_LPC176X/device/cmsis_nvic.h
- targets/TARGET_NXP/TARGET_LPC176X/device/flash_api.c
- targets/targets.json5
I ran into an issue when running the new network tests where the LPC1768 was running out of heap space. This MCU has two 32k banks of RAM, where one bank is used as heap, bss, and stack, half of the other bank is used for Ethernet buffers, and the second half of the third bank is unused.
This PR activates split heap support on the device, enabling all unused space to be used as heap. This nearly triples the amount of available heap on this target (if Ethernet is not used at least)! And it can now run the nanostack TCP test without crashing from running out of memory (though it still doesn't pass...).
- LPC1678 heap space increased to ~48k if Ethernet unused, or ~32k if Ethernet used
- LPC1768 linker script now supports memory bank configuration
None …
> LPC1768: Update linker script, support split heap

- connectivity/drivers/emac/TARGET_STM/TARGET_STM32F2/stm32f2_eth_conf.c
- connectivity/drivers/emac/TARGET_STM/TARGET_STM32F4/TARGET_ARCH_MAX/stm32f4_eth_conf.c
- connectivity/drivers/emac/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F429ZI/stm32f4_eth_conf.c
- connectivity/drivers/emac/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F439ZI/stm32f4_eth_conf.c
- connectivity/drivers/emac/TARGET_STM/TARGET_STM32F7/stm32f7_eth_conf.c
- connectivity/drivers/emac/TARGET_STM/stm32xx_emac.cpp
This PR fixes two issues with Ethernet multicast filtering on STM32. It's an update to my previous PR which added mcast filtering, but which I wasn't able to easily test the final version of (so some issues slipped through :( )
Issue 1: Hash table registers were swapped, meaning filtering wouldn't work once the perfect filter registers filled up
Issue 2: STM32 Eth IP v1 targets were calling HAL_ETH_ConfigMAC() after the point where I enabled mcast filtering, causing the register settings to get erased and all multicasts to be accepted regardless of filtering.
Multicast filtering should _actually_ work on STM32 targets now!
None
[X] Patch update (Bug fix / Target update / Docs …
> Fix multicast filtering on STM32

- TESTS/configs/greentea_baremetal.json5
- TESTS/configs/greentea_full.json5
- platform/mbed_lib.json
- platform/source/mbed_error.c
- tools/python/mbed_os_tools/test/host_tests/base_host_test.py
Quick PR to improve quality of life for us devs! Until now, if a Greentea test obviously died (HardFault or assertion failure), the test runner would just keep on truckin', waiting for the timeout to expire before failing the test. Since some tests (esp. network ones) can have timeouts up to 20 minutes, this could result in a lot of wasted time!
With this PR, the mbed_error() handler will now output a Greentea KV pair that tells the test runner "hey, this test crashed", so it can immediately end the test.
Should save some dev time during testing!
None
[X] Feature update (New feature / Functionality …
> Stop Greentea tests if a fatal error occurs

- targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/CMakeLists.txt
- targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/PinNames.h
- targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/clk_freqs.c
- targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/clk_freqs.h
- targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL46Z/CMakeLists.txt
- targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL46Z/clk_freqs.c
- targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL46Z/clk_freqs.h
- targets/targets.json5
- targets/upload_method_cfg/KL25Z.cmake
- targets/upload_method_cfg/openocd_cfgs/kl25z.cfg
Someone at work was giving away his old FRDM-KL25Z board, and I snapped it up! Now we can test Mbed on this target.
This board is one of the oldest and smallest targets that Mbed supports, and since this Freescale chip relies heavily on IDE generated code (Processor Expert) the entire Mbed HAL for it was handwritten by Mbed! 
This PR does some basic tasks to make life on this chip easier, including adding an upload method and fixing the old form factor (ARDUINO) which was causing a number of compiler warnings.
- KL25Z target builds without warnings
- KL25Z target now has an upload method config file
[] Patch update (Bug fix / Target update / Docs update / Test update / …
> Add KL25Z upload method support, upconvert ARDUINO form factor

- connectivity/drivers/emac/CompositeEMAC.md
- tools/cmake/UploadMethodManager.cmake
- tools/cmake/upload_methods/Finddfu_util.cmake
- tools/cmake/upload_methods/UploadMethodDFU_UTIL.cmake
- tools/cmake/upload_methods/UploadMethodSTM32CUBE.cmake
- tools/cmake/upload_methods/UploadMethodSTM32CUBE_DFU.cmake
This PR adds support for uploading over DFU. This is a prerequisite for working with Arduino STM32H7 boards, such as Portenta and Giga. These boards support DFU both via the Arduino bootloader and via the STMicro ROM bootloader. There currently isn't a defined way to enter the Arduino bootloader from Mbed however, so we'll have to rely on the ROM bootloader for now.
dfu-utils seems to be the standard way of doing this, so I added support for it in CMake. However, STM32Cube also supports DFU uploading, so it wasn't too tough to add an upload method for it as well.
- New upload method DFU_UTIL
- New upload method STM32CUBE_DFU
Updated the upload methods page: https://github.com/mbed-ce/mbed-os/wiki/Upload-Methods
------------------------------------------------------------------------------- …
> Add support for DFU upload methods

- storage/blockdevice/COMPONENT_QSPIF/source/QSPIFBlockDevice.cpp
Testing code for the Arduino Portenta, I noticed that its QSPI flash (MX25L12833F) was failing to init. Digging a bit deeper, it appears that it's hitting an [assert failure](https://github.com/mbed-ce/mbed-os/blob/7d6a1feee409954601d301769d476c32f116ea46/storage/blockdevice/COMPONENT_QSPIF/source/QSPIFBlockDevice.cpp#L1242) in `QSPIFBlockDevice::_enable_fast_mode()`. This function is trying to enable fast mode using the 3rd status register, but the flash only has 2 status registers, so it dies.
As [this comment](https://github.com/mbed-ce/mbed-os/blob/7d6a1feee409954601d301769d476c32f116ea46/storage/blockdevice/COMPONENT_QSPIF/mbed_lib.json#L23) explains, some flashes need this fast mode to hit their full clock frequency. However, MX25L12833F does not have a third status register and …
> Fix initializing Macronix QSPI flashes with only 2 status registers

- storage/filesystem/littlefsv2/include/littlefsv2/LittleFileSystem2.h
- storage/filesystem/littlefsv2/source/LittleFileSystem2.cpp
Noticed this [bug](https://github.com/arduino/ArduinoCore-mbed/issues/1042) on the Arduino bug tracker which is happening due to `this->_bd` being uninitialized in `LittleFileSystem2`, leading to undefined behavior if `unmount()` is called after constructing the class.
Should no longer crash in this situation.
None
[X] No Tests required for …
> littlefs2: Properly init class variables

- connectivity/netsocket/include/netsocket/Socket.h
- rtos/include/rtos/Thread.h
While working on the HTTP server example, I noticed some important info missing (or at least vague) in some of the docs for Thread and Socket. Cleaning that up here.
[X] No Tests required for this change (E.g docs only update) …
> Some minor doc improvements

- connectivity/drivers/emac/sources/CompositeEMAC.cpp
- storage/blockdevice/COMPONENT_SPIF/mbed_lib.json
- storage/blockdevice/tests/TESTS/blockdevice/general_block_device/main.cpp
- targets/TARGET_NUVOTON/nu_miscutil.c
- targets/targets.json5
- targets/upload_method_cfg/NUMAKER_IOT_M487.cmake
- targets/upload_method_cfg/NUMAKER_PFM_M487.cmake
I picked up an NUMAKER_PFM_M487 board last week and hooked it up to my greentea setup. It passed almost all the greentea tests! However, I did make some fixes:
- Added `COMPONENT_SPIF` since this board has an SPI flash -- now Mbed applications can use the flash easily!
- Remove PyOCD support as I was not able to get PyOCD to detect this board, and it didn't seem to me like it was supported
- Add some notes about upload methods for the board …
> Some fixes for NUMAKER_PFM_M487

- hal/include/hal/i2c_api.h
- targets/TARGET_STM/TARGET_STM32U0/stm_dma_info.h
- targets/TARGET_STM/i2c_api.c
- targets/targets.json5
- tools/cmake/upload_methods/UploadMethodOPENOCD.cmake
This PR fixes some bugs that were causing the I2C slave test to fail when running on STM32U0:
- Calling I2CSlave::frequency() after constructing the object would wipe out the I2C address in the registers, causing the I2C slave to not respond to any messages on the bus
- The slave read operation would erroneously return an error (0 bytes) if the master transferred less bytes than expected by the slave, instead of returning the actual number of bytes transferred.
This PR also enables I2C on U0 now that we've tested it with the test shield.
- I2C master and slave now supported for STM32U0
- I2C slave bugs fixes as above
None
[X] Patch update (Bug fix / Target update / Docs update …
> Fix I2C slave test on STM32

- targets/TARGET_STM/stm_dma_utils.c
This fixes the DMA ISR handlers not being defined with the right names for STM32U0.
Attempting to use DMA SPI on STM32U0 no longer causes a chip crash due to hitting a default IRQ handler
None
[] Tests / results supplied as …
> Fix incorrect DMA ISR handlers being used on STM32U0

- connectivity/drivers/emac/TARGET_STM/STM32EthMACv2.cpp
I found that, with master branch of Mbed, Ethernet did not work on STM32H723. After some debugging and A/B testing, I narrowed it down to this line, which I somehow lost when porting code over from the STM32Cube HAL.
Oddly, without this line, Ethernet still manages to work on STM32H743 and H745/H747. However, it completely can't initialize on STM32H72x.
I also _suspect_ this might be related to a very intermittent issue I've been seeing on STM32H747 where Ethernet sometimes loses packets. However, I'm not totally sure.
None
[] Major …
> Fix missing SYSCFG_CLK_ENABLE() for STM32H7 Ethernet

- targets/TARGET_NUVOTON/TARGET_M480/TARGET_NUMAKER_PFM_M487/PinNames.h
- targets/TARGET_NUVOTON/TARGET_M480/i2c_api.c
- targets/targets.json5
I am working on testing the M480 board using our [CI Test Shield](https://github.com/mbed-ce/mbed-ce-ci-shield-v2), which can do exhaustive tests of things like I2C, SPI, and PWM to ensure that they are implemented correctly. These tests are much more in-depth than the tests that ARM's CI shield did, and should be able to root out a great deal more issues.
First step was testing I2C, and the M480 was actually VERY close to passing all the tests -- I'm impressed, few boards I've tested have worked this well out of the box!
However, I did find two small issues in the I2C implementation that should be addressed:
- When doing a read with the asynchronous API, the MCU sends a repeated start at the end of the transaction instead of a stop
- When doing a slave receive, the last byte gets NACKed …
> Fix some M480 I2C issues causing test shield test failures

- targets/TARGET_STM/TARGET_STM32H7/linker_scripts/STM32H7Ax_FAMILY/STM32H7Ax.ld
- targets/cmsis_mcu_descriptions.json5
Use AXI SRAM for main memory and AHB SRAM for additional heap on STM32H7Ax family.
Fix wrong IROM1 size on STM32H7A3ZITxQ and STM32H7B3ZITxQ(was 128KB, should be 2MB).
After Split Heap was implemented on STM32H7, any heap allocation on STM32H7Ax family will fail with an "Out of Memory" error. Comparing the linker script of STM32H7Ax_FAMILY and STM32H743_STM32H72x_FAMILIES, I found the former script uses AHB SRAM as main memory and AXI SRAM as additional heap, but the latter one uses AXI SRAM as main memory and AHB SRAM as additional heap. The current Split Heap implementation requires the additional heap to be placed at a higher address than the main memory. Given the fact that AXI SRAM starts at 0x24000000 and AHB SRAM starts at 0x30000000, the current linker script of STM32H7Ax_FAMILY …
> Fix heap allocation on STM32H7Ax family

- targets/TARGET_STM/TARGET_STM32H5/CMakeLists.txt
- targets/TARGET_STM/TARGET_STM32H5/flash_api.c
- targets/TARGET_STM/can_api.c
- targets/targets.json5
Enables CRC, FLASHIAP and CAN features for the STM32H5 family.
This PR passed the CRC and FLASHIAP Greentea tests on NUCLEO-H563ZI.
The CAN part was tested using a modified "CAN hello, world" program that uses CAN1 to send data frames to CAN2 on the same board, and verify the id, length and content of the received frames. The test was done on a custom STM32H563VI board and also on a custom STM32H723ZG board with two external TJA1050 modules, in three baud rates(250kbps, 500kbps, 1Mbps) and two frame formats(Standard and Extended). STM32H7 is affected by this PR because it fixed the wrong values used in the DataLength field of FDCAN_TxHeaderTypeDef structs(The FDCAN data length code values are different in the H5, H7, U5 series and in the L5, G0, G4 series). 
None …
> Enable CRC, FLASHIAP and CAN for STM32H5 

- targets/upload_method_cfg/SFE_ARTEMIS_ATP.cmake
- targets/upload_method_cfg/SFE_ARTEMIS_NANO.cmake
- targets/upload_method_cfg/SFE_ARTEMIS_THING_PLUS.cmake
- targets/upload_method_cfg/common/SFE_ARTEMIS_DK.cmake
- targets/upload_method_cfg/common/sparkfun_artemis.cmake
- tools/cmake/mbed_python_interpreter.cmake
- tools/cmake/upload_methods/UploadMethodAMBIQ_SVL.cmake
- tools/pyproject.toml
- tools/python/ambiq_svl/README.md
- tools/python/ambiq_svl/__init__.py
- tools/python/ambiq_svl/svl.py
This PR adds an upload method for the Ambiq Apollo3 SVL bootloader. This lets you program SparkFun Artemis boards without the use of an external SWD programmer.
- AMBIQ_SVL upload method added
- svl.py Python script is now bundled with Mbed. It is not pip installable and it's a single <500 line file, so it seemed simplest to just add it to Mbed so that the user doesn't have to manually clone it somewhere.
- All Artemis boards now have upload method config files
Will add section to upload methods page once this is ready to merge
[] …
> Implement AMBIQ_SVL upload method for Ambiq Apollo3

- platform/source/mbed_board.c
- targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/gpio_api.c
- targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/objects_gpio.h
This PR simplifies and standardizes the PinMode enum on Apollo3. Previously, this enum contained every possible pin setting it was possible to set on the device, even ones that didn't really make sense (e.g. disabling the input so it reads as 0). Now, this enum is much simpler and only contains pin modes that are (semi-)standard across other Mbed targets.
I also fixed an issue where if a pin was configured as an open-drain output, reading it would always return the written state of the pin instead of its actual electrical state.
- Apollo3 pin name constants now have standardized names
- Removed Apollo3 pin name constants whose functions aren't obvious or standardized
- Fixed bug with reading open drain DigitalInOuts on Apollo3
I'll add a note to the docs site about how only IO_20 has a …
> Apollo3: Simplify and standardize pin modes

- targets/TARGET_STM/sleep.c
On STM32 microcontrollers, the ForceOscOutofDeepSleep function is called after wake-up from deep sleep, to setup an initial system clock. Inside this function, RCC_MSIRANGE_11 is used to specify the MSI clock frequency for STM32L4, STM32L5 and STM32U5 series. Unfortunately, RCC_MSIRANGE_11 has different a meaning in STM32U5 than in STM32L4 and STM32L5. In STM32L4 and STM32L5, RCC_MSIRANGE_11 stands for 48MHz which is the highest MSI frequency. But in STM32U5, RCC_MSIRANGE_11 means just 768KHz. To use the highest MSI clock frequency (48MHz) on STM32U5, we need to change the MSI clock range to RCC_MSIRANGE_0. 
None.
[X] Patch update (Bug fix / Target update / Docs update / Test …
> Fix the slow wake-up of STM32U5 from deep sleep

- platform/include/platform/mbed_assert.h
- targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/analogin_api.c
- targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/device.h
- targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/gpio_api.c
- targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/iom_api.c
- targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/objects.h
- targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/pinmap.c
- targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/serial_api.c
I noticed while doing other testing that code did not run on the Apollo3 when Mbed was configured in Release mode (worked fine in Develop). After a bit of digging, I realized that this was happening because some of the am3 HAL calls weren't being executed. This, in turn, was happening because they were wrapped in `MBED_ASSERT()` expressions, and everything inside MBED_ASSERT is _compiled out_ in Release mode. Apparently the people who developed the HAL layer for this target (including me :cry: ) didn't realize this.
To fix this, I added a new macro called `MBED_CHECK_AM_HAL_CALL` which performs a similar function to the asserts, but always evaluates its arguments. Then I used a regex to replace all of the assert calls with this macro.
- Code now runs on Apollo3 in Release mode.
None …
> Apollo3: fix Mbed not booting in release mode
